### ISSUE TITLE
Marry Issue (lock proposer)

### ISSUE THREAD

**Issue by rosieneko** [veldlabs/miki-bot#10]
In latest IA build, 

Proposer is NOT locked from being proposed to, which can break.

E.g.,

Person A is married 4 times. They propose to Person B.
Person C proposes to Person A.

Person B accepts marriage. Person A accepts marriage.

Now Person A is married to 6 people, over the maximum amount.

You could essentially cause a chain like this, though I think 6 might be the max.

**Comment by velddev** [comment]
Done!
