### ISSUE TITLE
Documentation Errors

### ISSUE THREAD

**Issue by LovingMelody** [veldlabs/miki-bot#101]
# Missing Documentation
### I was helping someone with Miki the other day, and by helping i mean, I was planning on linking them to the docs, it was then i noticed that things were missing
----
##  Docs Errors:

* ``>toggleerrors`` is missing from docs (should be under setting)
* ``>syncname`` is missing  from docs (should be under accounts)
* ``>syncavatar`` is missing from docs (should be under accounts)
* ``>buymarriageslot`` is missing from docs (should be under Marriage)
* ``>setrolelevel`` is missing (should be under Admin)
*  ``Setting`` should be renamed to ``Settings``

**Comment by velddev** [comment]
@xialight summoning session

**Comment by Numailia** [comment]
there's a lot more than this missing tbh, the docs being outdated and poorly written is a known issue

**Comment by LovingMelody** [comment]
Ik, I just didnt have time to go around and see what all is missing

**Comment by velddev** [comment]
This is getting updated now.
