### ISSUE TITLE
Miki Told me to send this

### ISSUE THREAD

**Issue by kiralasani** [veldlabs/miki-bot#102]
![image](https://cloud.githubusercontent.com/assets/23621041/25484851/971a45b2-2b29-11e7-8756-18ddd6821d4b.png)

**Comment by velddev** [comment]
Tell me about your avatar, is it a gif or a png? also try again

**Comment by kiralasani** [comment]
It's a jpg, but you fixed it! thanks!

![image](https://cloud.githubusercontent.com/assets/23621041/25487708/02a2d9ee-2b33-11e7-86ab-c332f1547095.png)
