### ISSUE TITLE
>give not working

### ISSUE THREAD

**Issue by xladyari** [veldlabs/miki-bot#103]
![capture](https://cloud.githubusercontent.com/assets/28109702/25494090/7ccf97b2-2b46-11e7-93bf-23675aa86c40.PNG)

**Comment by velddev** [comment]
Make sure you use the command like this

`>give @veld 1000`
`xxxxx user     amount`

**Comment by xladyari** [comment]
yeah I did.

**Comment by xladyari** [comment]
It just sends this error

**Comment by velddev** [comment]
Hmm. I haven't seen this one yet. Please try whenever now. And report if it's resolved

**Comment by velddev** [comment]
Fixed
