### ISSUE TITLE
>Info Command NOT WORKING

### ISSUE THREAD

**Issue by SalusKrhyme** [veldlabs/miki-bot#104]
I have tried for the last 3 days at many moments of the day when Miki was online, and it still never gave me the achievement. My profile has " info (286) " 
286 confirmed >info commands. Yet no achievement. 
It leads me to ask, if this achievement is bugged/not working, what about the special phrases we have to say for the secret achievements? What if we already said them?

**Comment by velddev** [comment]
This has been fixed
