### ISSUE TITLE
Multi Achievement bug (same achievement)

### ISSUE THREAD

**Issue by Jasdavros** [veldlabs/miki-bot#105]
![multi unlucky achievement](https://cloud.githubusercontent.com/assets/28059996/25513756/cf2dd7b2-2ba5-11e7-8e47-f2f480493806.PNG)

**Comment by davpfre** [comment]
How can the bug be reproduced? Tell what you did.

**Comment by velddev** [comment]
Obviously by unlocking it.

**Comment by Jasdavros** [comment]
Type >roll 0

**Comment by Jasdavros** [comment]
Once you get the achievement the first time
(For me was when I first tried to roll the dice and it Mike gave me the achievement in PM and fed back the result 1) but every time after that it will always feed an error but give you the achievement instead of properly reporting an error

**Comment by velddev** [comment]
This has been fixed in 0.2.3
