### ISSUE TITLE
The >safe command returns an error when a tag wasn't found.

### ISSUE THREAD

**Issue by davpfre** [veldlabs/miki-bot#106]
![image](https://cloud.githubusercontent.com/assets/6499570/25521306/568fbdfc-2bff-11e7-97b4-24e709e1d96f.png)

![image](https://cloud.githubusercontent.com/assets/6499570/25521082/9c0659aa-2bfe-11e7-8f56-d660b120ca37.png)

**Comment by velddev** [comment]
This has been fixed in 0.2.3
