### ISSUE TITLE
Miki told me to screenshot and send this

### ISSUE THREAD

**Issue by BlueSerenity** [veldlabs/miki-bot#107]
![image](https://cloud.githubusercontent.com/assets/20779395/25531644/76f15544-2bf8-11e7-8fb2-695807fa3dfd.png)

**Comment by davpfre** [comment]
How did this error happen?

**Comment by velddev** [comment]
Thanks, this is enough to track and fix it :)

**Comment by velddev** [comment]
This has been fixed in 0.2.3
