### ISSUE TITLE
">pasta delete" bug

### ISSUE THREAD

**Issue by PedroPhilippiAraujo** [veldlabs/miki-bot#111]
![captura de tela 22](https://cloud.githubusercontent.com/assets/28170871/25551632/f528ecdc-2c5d-11e7-95e1-4fe22347dde3.png)

**Comment by Numailia** [comment]
which command is this for? also, update your title to something useful please

**Comment by velddev** [comment]
Seems like the pasta you tried to delete was no longer available.
