### ISSUE TITLE
">give" code "gives" an error

### ISSUE THREAD

**Issue by FellDragonGrima** [veldlabs/miki-bot#113]
![image](https://cloud.githubusercontent.com/assets/28196509/25556720/a97ff20e-2ccf-11e7-872e-c8f92a36a45a.png)
I hope this helps you!

**Comment by hnnmilam** [comment]
Make sure you used it in the right form: >give @user amount
for example >give @FellDragonGrima 100
Also check duplicate topic

**Comment by FellDragonGrima** [comment]
Yeah, I know how to do it, but it never works correctly for me. I do >give
@Example#1234 50, which I believe is correct, but even then it still didn't
seem to work. It's working now, so thank you whoever did that 👌

**Comment by velddev** [comment]
Seems to be a minor issue with spacing.
