### ISSUE TITLE
>server enable command nsfw // error

### ISSUE THREAD

**Issue by RavenVentail** [veldlabs/miki-bot#115]
![error](https://cloud.githubusercontent.com/assets/28210959/25561166/d962a372-2d65-11e7-9b35-f34d515ae359.PNG)

**Comment by velddev** [comment]
Please send the full embed ><

**Comment by hnnmilam** [comment]
Isn't this is what happens when you try to enable/disable a command that doesn't exist?

**Comment by IA-Xerise** [comment]
Same as #119
