### ISSUE TITLE
Toggling a non-existant entity returns a error. 

### ISSUE THREAD

**Issue by mlgkirito** [veldlabs/miki-bot#119]
![image](https://cloud.githubusercontent.com/assets/28245028/25571226/5dba6a5c-2de2-11e7-8c03-850fce86f446.png)

**Comment by velddev** [comment]
This has been implemented very recently. You tried to disable and/or enable something that's non-existant.

**Comment by mlgkirito** [comment]
I can't get the nsfw thing to work on my server with nsfw chat active and it gave me that error so I was wondering if there's a fix and tried to enable it through the commands list that said how to disable a module. Tried the disable nsfw module but that's what came up. I can't figure out how to get NSFW working with my server anymore.

Also miki bot said I became lvl 8 when I was already lvl 9 before hand so that makes no sense.

![image](https://cloud.githubusercontent.com/assets/28245028/25616774/7df8151e-2ef3-11e7-9e9e-cbc8d1f77e36.png)

![image](https://cloud.githubusercontent.com/assets/28245028/25616782/8efb3062-2ef3-11e7-8817-48f8deeefd52.png)

**Comment by IA-Xerise** [comment]
__**Why was >nsfw and >ecchi removed?**__
The >nsfw and >ecchi command went against Discord's term of service and interfered with Veld's chance of getting a Discord Partnership. As a result, a poll was used to determine whether >nsfw and >ecchi should stay and the majority voted to get a Discord partnership over keeping the NSFW commands. We might reimplement the commands in the future.
As for the Level up it was most likely your global level that was 9 and she announced your local level reaching 8
