### ISSUE TITLE
NSFW and Ecchi disable

### ISSUE THREAD

**Issue by ghost** [veldlabs/miki-bot#12]
When I disable the nsfw and ecchi settings on the channels I don't want it on, it will re-enable after a while, allowing everyone to use the command again.

**Comment by ghost** [comment]
I may have figured out the problem. If any text channels are changed? or created, it will reset the nsfw and ecchi settings. I don't know if it resets anything else.

**Comment by velddev** [comment]
If you delete and remake the channel, it does remove the data. yes.

**Comment by ghost** [comment]
About a couple hours ago, without touching any of the channels, the ecchi command became available again to use by everyone for one channel and then shortly after, another. However, the nsfw command remained disabled for all channels. As for making channels, making a completely new channel (not remaking a channel) will remove the data as well for all the other channels.

**Comment by velddev** [comment]
I'll look into it

**Comment by velddev** [comment]
This has been fixed in 0.1.9
