### ISSUE TITLE
profile error message

### ISSUE THREAD

**Issue by Heartscythe** [veldlabs/miki-bot#125]
![capture](https://cloud.githubusercontent.com/assets/28376846/25688186/1ba79214-304b-11e7-989b-e6ecbd73c46a.PNG)

**Comment by TheGlugGlugPug** [comment]
![screenshot 6](https://cloud.githubusercontent.com/assets/28493993/25776460/e2a63988-327b-11e7-8f75-4fcb42a27b6d.png) I have a problem with the >profile command
