### ISSUE TITLE
Error running server command

### ISSUE THREAD

**Issue by ghost** [veldlabs/miki-bot#131]
![capture](https://cloud.githubusercontent.com/assets/23655460/25744542/9181758c-31ee-11e7-85f2-4850dd8ef564.PNG)

**Comment by ChipDipMoneyCows** [comment]
i keep getting that for almost every command

**Comment by raf802** [comment]
I too get this. I typed ">server enable command nsfw" as the command ">nsfw mommygf" and ">ecchi" did nothing.

**Comment by velddev** [comment]
Nsfw is currently disabled, thus cannot be enabled
