### ISSUE TITLE
Giving Commands and It Doesn't Respond

### ISSUE THREAD

**Issue by ChipDipMoneyCows** [veldlabs/miki-bot#132]
So I created a server for me and my friends and it's all about NSFW. (We didn't put it on our other chatroom because we don't like to have NSFW in that one.) I got a bunch of bots because I wanted to have an assortment of things to do on there so it wouldn't be a boring server. I saw a lot of servers with Miki bots so it seemed like a great idea. And it was. 
I was going through all of the commands to make sure they worked some time later on, maybe a couple of days, and I typed in >nsfw yaoi to check and it didn't work. I tried multiple times with several different commands like >slap >kiss >cuddle but none of them seemed to be working.
I think this is a glitch? Or is it because I have 13 bots?

**Comment by hnnmilam** [comment]
1. well, >nsfw doesn't work rn
2. Try ''miki.prefix >''
3. Make sure Miki has permission to ember links in that channel

**Comment by rosieneko** [comment]
Closing this ticket. Miki does not have any nsfw commands at the moment, but Veld is supposedly bringing it back.
