### ISSUE TITLE
Miki isnt working in discord help!?

### ISSUE THREAD

**Issue by BlackSteelToeTom** [veldlabs/miki-bot#136]
![Uploading 20170510_122017.jpg…]()

**Comment by IA-Xerise** [comment]
Can you please post the full version once you have access to your desktop?

**Comment by velddev** [comment]
Every give command that is here is the same error @ia-xerise

**Comment by BlackSteelToeTom** [comment]
@velddev what do I have to do now?

**Comment by velddev** [comment]
I've resolved your issue:)
