### ISSUE TITLE
>Give wont let let me send mekos help!?

### ISSUE THREAD

**Issue by BlackSteelToeTom** [veldlabs/miki-bot#139]
![screenshot_20170510-204558](https://cloud.githubusercontent.com/assets/28580099/25928520/447de9aa-35c2-11e7-9f11-2fb341de96e7.jpg)

**Comment by BlackSteelToeTom** [comment]
@IA-Xerise how do I know if the problem is fixed!? I mean of course Im still not getting any results so do I wait some more or send another one?

**Comment by velddev** [comment]
If you're using a phone, try to avoid double spaces. they happen a lot
