### ISSUE TITLE
I was told to post this here "You used the 'server' and it crashed!"

### ISSUE THREAD

**Issue by Neospell** [veldlabs/miki-bot#144]
![image](https://cloud.githubusercontent.com/assets/16720258/26031681/93473e9e-384a-11e7-8689-1760c80617ed.png)

**Comment by Neospell** [comment]
Extra details if this helps i tried to use >ecchi and >nsfw and they didn't work so i tried to enable them thinking maybe they came disabled and got this no error is given using the commands just nothing is said

**Comment by velddev** [comment]
Those commands were removed but will come back.
