### ISSUE TITLE
>toggleerror Doesn't work

### ISSUE THREAD

**Issue by LovingMelody** [veldlabs/miki-bot#149]
Just noticed that I cant use >toggleerror to disable, also it should be \`\`>toggleerror\`\` it's currently \`>toggleerror\`

**Comment by velddev** [comment]
I honestly have no clue what you mean with this.

**Comment by velddev** [comment]
It's >toggleerrors by the way.

**Comment by LovingMelody** [comment]
![image](https://cloud.githubusercontent.com/assets/17859309/26211832/781e55ce-3bc1-11e7-8c46-b95888543753.png)
Miki says otherwise

**Comment by LovingMelody** [comment]
@velddev in your next update.. can you please just add an s.... to the end...
