### ISSUE TITLE
Miki doesn´t respond to ecchi command

### ISSUE THREAD

**Issue by ghost** [veldlabs/miki-bot#150]
Miki doesn´t respond to this command or the nsfw, the command also can´t be disable or enable, it sends this error message
![73e365eb75cdf42383dc7be1269752ab](https://cloud.githubusercontent.com/assets/28767246/26179187/bada0d6c-3b27-11e7-84a3-886c4b9fd861.png)

**Comment by Phanrazak** [comment]
Those commands were removed for the time being
