### ISSUE TITLE
Documentation, (this time not the wiki)

### ISSUE THREAD

**Issue by LovingMelody** [veldlabs/miki-bot#155]
![image](https://cloud.githubusercontent.com/assets/17859309/26380243/750186c6-3feb-11e7-856c-73f8b0d564fe.png)
Once again, I am here leaving an issue. Please at least have information in ``>help`` if you are not going to update the wiki.

**Comment by taxilly** [comment]
The wiki has mostly been moved over to the Miki site.
The [Miki commands page](http://miki.veld.one/commands/) has a list of everything in detail. Simply search for `slots`/`gambling`.

**Comment by LovingMelody** [comment]
The readme should be updated to state that, but the >help command should still be properly documented, but can lack some of the detail.

**Comment by hnnmilam** [comment]
Actually most of command doesn't have this. But many commands are very simple so it's not necessary imo. But yeah, this should be added, just not now ~~since there're more important issues haven't been fixed yet~~

**Comment by taxilly** [comment]
I think Veld is re-writing the databasing for Miki atm - so just give him some time, things will get fixed.

**Comment by LovingMelody** [comment]
Issues do not mean they have to be addressed right away, it just so they dont get overlooked. @IA-Xerise just marked it as an enhancement. meaning its not urgent, or that would of beed marked as well.

**Comment by velddev** [comment]
I've added most of the new lines.

**Comment by velddev** [comment]
Most of these are in now.
