### ISSUE TITLE
Softabn Error

### ISSUE THREAD

**Issue by gotsteez** [veldlabs/miki-bot#156]
![image](https://cloud.githubusercontent.com/assets/28912400/26382876/8718945a-3ffd-11e7-9ddd-1a339d3ca0e8.png)

**Comment by LovingMelody** [comment]
@zMrKrabz  please include a screenshot of the command executed, Veld is a baka and doesn't include it in the error.

**Comment by Pao-Lumu** [comment]
Issue recommended for closure.
AdminModule.cs has been entirely rewritten since report.
Additionally, the command that caused the error was not supplied, so this is not reproducible.
~ty Phan~
