### ISSUE TITLE
Known >profile issues

### ISSUE THREAD

**Issue by rosieneko** [veldlabs/miki-bot#16]
Hey Veld, I know you know these things, but writing it down so people can just check this and know / update with a comment if they have more information.
- Nickname/event changes do not take effect automatically. There is a long delay before changes will take effect. Sometimes the change has to be forced manually (by me).
- Profile doesn't load for some people. Sometimes it breaks after people marry each other. This is not consistent, as it will sometimes start working again for Person A, but then break later for Person A (even if they haven't done anything.
- During the time that the profile does not work, it seems that the DB is not updating and recording exp points (only tested on one user for a very short amount of time). Could this be a delay between shard to DB?

**Comment by velddev** [comment]
This has been fixed in 0.1 9
