### ISSUE TITLE
>Divorce

### ISSUE THREAD

**Issue by Eimantas22** [veldlabs/miki-bot#173]
cant divorce
Keeps saying error
![ffafdaf](https://cloud.githubusercontent.com/assets/20424351/26832114/4d0a95dc-4ac6-11e7-8a28-7a18e63ab4bf.png)

**Comment by CritJ** [comment]
To give a bit more context to this. After receiving the divorce error I can now type >acceptmarriage @ over and over again. But said person and I never get married via our profiles.

**Comment by velddev** [comment]
The person you're trying to divorce doesn't exist.

I'll look into this soon.

**Comment by CritJ** [comment]
![screen shot 2017-06-06 at 9 21 20 am](https://cloud.githubusercontent.com/assets/29221050/26833968/913de984-4a99-11e7-970e-9944938d13a0.png)

**Comment by CritJ** [comment]
In regards to what I mentioned we have worked it out. The other person had to >declinemarriage and everything is normal now.

**Comment by LovingMelody** [comment]
#151 could help solve this issue, by telling the user what is wrong and not giving them a massive error log.

**Comment by velddev** [comment]
This should be resolved.
