### ISSUE TITLE
Marriage not displaying on profile

### ISSUE THREAD

**Issue by HEIII4** [veldlabs/miki-bot#174]
I married somebody but it is not displayed at the proifle how it should be... It is working at other friends.

![image](https://user-images.githubusercontent.com/29236862/26845969-99972730-4af8-11e7-8687-5b150b62c05b.png)

**Comment by CritJ** [comment]
Hi, I had this issue and what me and my friend did to fix it was both >declinemarriage @whomever. Then you can marry as usual.

**Comment by velddev** [comment]
This is fixed in a old update
