### ISSUE TITLE
Stuck after >divorce

### ISSUE THREAD

**Issue by AdrienBoitelle** [veldlabs/miki-bot#177]
Hello, after my friend used >divorce on me, we cannot re-marry anymore, nor send proposals

https://image.prntscr.com/image/6CEvaBX9TrCBiNN3QumR1A.png
https://image.prntscr.com/image/ji3oa0g-SPWPoqMEkUl20g.png

I believe this is a bug and not a feature :)

**Comment by CritJ** [comment]
You and the other person need to >declinemarriage then it should be fixed

**Comment by velddev** [comment]
This has been resolved in the latest marriage update.
