### ISSUE TITLE
Miki shows blanks after A command

### ISSUE THREAD

**Issue by KieranStone** [veldlabs/miki-bot#179]
![img_20170615_021936](https://user-images.githubusercontent.com/29448390/27168067-fcecc446-5171-11e7-9012-861641bfb163.jpg)

**Comment by KieranStone** [comment]
Is this another problem in the works or do I need to do something please fix
Thank you...

**Comment by LovingMelody** [comment]
Please verify that Miki has embed permissions, as this can happen if it is missing

**Comment by velddev** [comment]
Fuzen is right, Add the "Send Link Embed" in message settings
![image](https://user-images.githubusercontent.com/13852840/27217710-44c29fc0-527b-11e7-8039-ee46292c5d94.png)
