### ISSUE TITLE
All of the commands stopped working?

### ISSUE THREAD

**Issue by invaderxyz** [veldlabs/miki-bot#18]
![error](https://cloud.githubusercontent.com/assets/23371179/20162998/8e0665f4-a6be-11e6-8091-475eb6a7c75f.png)

i dunno she just kinda suddenly stopped working?? like we still get achievements and levels but the commands dont work. we think she is planning a bot rebellion.

**Comment by velddev** [comment]
Did you use >prefix?

**Comment by rosieneko** [comment]
I see that the >prefix is being used but Miki is not responding to anything but direct mention chat. Miki also has the ability to have her prefix changed to something else; could it be that the prefix was changed?

**Comment by invaderxyz** [comment]
I went back a few days and the prefix was changed to DM, however I can't change it back? Like she doesn't respond to using DM as a prefix.

**Comment by velddev** [comment]
Can you post your server id? you can find it by setting your discord to developer mode
![img1](https://a.pomf.cat/tbxbmr.png)
and then copying the serer id:
![gif1](https://a.pomf.cat/zbiqae.gif)

**Comment by invaderxyz** [comment]
The ID is 160105994217586689.

**Comment by velddev** [comment]
Are you sure you picked the server's ID? I cannot find your ID in my database.

**Comment by velddev** [comment]
Also feel free to drop a invite to the server, so i can try and fix it.

**Comment by invaderxyz** [comment]
Yep! and the invite link is <link removed> (though i'm gonna remove it right after you join)

**Comment by velddev** [comment]
Your problem has been resolved. Thanks for your cooperation.
