### ISSUE TITLE
>invite does not give a proper link

### ISSUE THREAD

**Issue by LovingMelody** [veldlabs/miki-bot#180]
Issue:The invite command does not properly state what permissions Miki needs
Solution: this can be fixed by adding permission scope this will prevent issues like #179

**Comment by velddev** [comment]
Good point, I'll resolve this in 0.3.3

**Comment by velddev** [comment]
This has been resolved  as of commit [ccec421](https://github.com/velddev/miki/commit/8fa4084579e8a47422a312bda07fef58138091c5)
