### ISSUE TITLE
Miki is unresponsive

### ISSUE THREAD

**Issue by KikiKitten** [veldlabs/miki-bot#182]
Miki seems to randomly stop responding all together, sometimes responding minutes later without any sign of warning. There has been no edits to prefixes or any form of tampering so I am unsure what the issue is. She even went offline for a moment. I was wondering if her activity of 'Playing 1/24' has anything to do with it? It sometimes switches to '0/24' so I wondered. Please help!

**Comment by LovingMelody** [comment]
Miki is under a lot of load and keeps getting rate-limited for some reason. Veld is currently dealing with life things and hasn't had too much time to fix this problem. As for the ``Playing x/x`` it is just an identifier on what [shard](https://discordapp.com/developers/docs/topics/gateway#sharding) you have. Hope this helps and sorry for the inconvenience.

**Comment by velddev** [comment]
This has been fixed :)
