### ISSUE TITLE
marriage display in new profiles

### ISSUE THREAD

**Issue by moonbok** [veldlabs/miki-bot#196]
I'm upset about the way the new profiles look. I didn't spend thousands upon thousands of mekos on extra marriage slots (and donate actual human money to you for even more marriage slots) just to have 10 of my marriages hidden from my profile. Please tell me this change isn't here to stay; I really want to be able to see all of my marriages on my profile. 

Also, I was wondering if the profiles will ever be fixed so that our marriages show up in chronological order again.

**Comment by velddev** [comment]
Hey, thanks for your issue, I'm looking into ways to fix this, it seems to be a well demanded feature. I'll revert this soon, as for the chronological order, I'll look into this as well. Hopefully you're not too upset :(

**Comment by moonbok** [comment]
Thank you so much! Sorry for being overly dramatic about it lol I'm not
THAT upset really. <3 Keep up the great work!

**Comment by velddev** [comment]
Hey moonbok, 

I've reverted the marriage cutoff and ordered them on chronological order from this update on. Thanks for your feedback

**Comment by moonbok** [comment]
Thank you so much!!
