### ISSUE TITLE
Suggestion: Enhance >guildprofile with invite link to rival

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#199]
Allow server admins to submit an invite link to Miki using something like >addinvite "link" or something to that effect. Include the submitted link in the guildprofile information so users are able to easily access their rival guild.

**Comment by velddev** [comment]
This is a bad idea, this means miki will allow random people in your server, not everyone would want this.

**Comment by adv0catus** [comment]
It's opt-in.

**Comment by adv0catus** [comment]
If the server admin changes their mind, they can just kill the invite link. If you want a more "official" method, add a >deleteinvite command to remove invite link from DB.
