### ISSUE TITLE
Disabling >marry is not functional?

### ISSUE THREAD

**Issue by SecundusLullaby** [veldlabs/miki-bot#2]
I think the title tells pretty much everything 😄

**Comment by rosieneko** [comment]
Adding additional notes. Broken:

> disable marry
> disable acceptmarriage

Enabling works for both these commands.

**Comment by SecundusLullaby** [comment]
Thanks :)

**Comment by velddev** [comment]
Yes. You cannot disable accept/decline because they're mere helper commands

**Comment by rosieneko** [comment]
Except you can enable/disable declinemarriage :^]. That's why I did not list that one.

**Comment by velddev** [comment]
fixed in 1.8.1
