### ISSUE TITLE
NSFW command permission checking

### ISSUE THREAD

**Issue by LovingMelody** [veldlabs/miki-bot#200]
Currently the NSFW commands check if the channel has "nsfw" in its name, discord has changed this so nsfw channels don't have to have nsfw in the name, it has a separate channel property now.

**Comment by velddev** [comment]
This is a property from Discord.Net, it'll resolve itself once i update to the newest version.

**Comment by velddev** [comment]
Also if you look in the code, more specifically [here](https://github.com/velddev/Meru/blob/master/Meru.SDK/Interfaces/IDiscordMessageChannel.cs) you can see that there is a property.
