### ISSUE TITLE
Splitting `>toggleguildnotifications` into `>togglelevelnotifications` and `>toggleachievementnotifications` 

### ISSUE THREAD

**Issue by xialight** [veldlabs/miki-bot#204]
Some people may prefer showing either only level notifications or achievement notifications as oppose to toggling them all off.

**Comment by velddev** [comment]
After doing some research on this I will split both notifications, but, levelling will also have the options of only showing when rewards are given.

the option set will look like this:

```
"level_up" {
   ALL (default)
   REWARDS_ONLY
   NONE
}

"achievements" {
   ALL (default)
   NONE
}
```
