### ISSUE TITLE
Mekos Disappearing from account

### ISSUE THREAD

**Issue by xialight** [veldlabs/miki-bot#206]
An user shown that he gave 10k mekos to a friend so he can get one of the money achievements. However, the mekos were lost when the friend tries to give 10k mekos back to him.
![](http://i.imgur.com/5uWADlr.png)
![](http://i.imgur.com/3mXgoZn.png)
![](http://i.imgur.com/OTNssdu.png)

**Comment by velddev** [comment]
Same issue (codewise) as #205
