### ISSUE TITLE
>guildnewrival

### ISSUE THREAD

**Issue by Lyra13** [veldlabs/miki-bot#208]
I don't quite understand the point of the update. Now you can only use the >guildnewrival command once every day. I see no good side to that, but I see a bad side to it. I now can't change our rivals to be rivals that we can beat within a week, once a week. My plan was to switch rivals every Friday, keep switching them till we have rivals that we can beat till next Friday, and then try to beat them. Now if we generate a way to over powered or shitty guild, we'd have to wait a day to switch.

**Comment by velddev** [comment]
Yes, basically this is the idea. It's not really designed for people to just press "new" every 25 seconds until they can receive mekos.
