### ISSUE TITLE
Public server announcements

### ISSUE THREAD

**Issue by davpfre** [veldlabs/miki-bot#209]
As a guild owner, creating a message to be sent to a channel at a specific time, would be a powerful utility. fx, every hour post the server rules. Or posting a link, two times every sunday.

A lot of people have requested this feature and many other bots already have this feature. It may be possible and it could be really useful.

maybe even having the capability to mention everyone.

**Comment by adv0catus** [comment]
Perhaps it'd be better served as a PM-side feature? Admin can use something like `>msg {message}` and then when a user does `>msg>`, Miki PM'd the message.

**Comment by davpfre** [comment]
That wasn't originally my idea. Though you could open an issue suggesting it.

**Comment by adv0catus** [comment]
i'm aware it's not the original idea. making a suggestion that would possibly have better functionality and usability.

**Comment by binn** [comment]
@adv0catus Discord's TOS wouldn't approve of your idea and yes @davidfrp it's possible using timers and weebhooks 👍

**Comment by davpfre** [comment]
@binsenpai I know it is possible. Also... this is over a month old idea, please avoid necroposting.

**Comment by LovingMelody** [comment]
It's ok to necropost, this isn't a forum. If the issue is open you can comment on it.

**Comment by davpfre** [comment]
I know what GitHub is, thanks. I was just thinking the mention was completely unnecessary for a month old issue. No new light was being shedded on the issue. If you're going to ping me, make it worth my while.

**Comment by velddev** [comment]
~~A good idea is to allow admins to do an @ everyone without giving them the ability of abusing it. but this could is more of a thing where you let miki do your announcements.~~

Actually I like this idea, I'll add it at a time whenever I can
