### ISSUE TITLE
I am unsure of the >guildnewrival command.

### ISSUE THREAD

**Issue by Tyzlerr** [veldlabs/miki-bot#210]
I was goofing around in my Discord chat when most of my members are normally offline and I accidentally did >guildnewrival @oneofmymembers thinking it would officially make me and that person rivals (There is a lot of competition over Miki's number one spot there) and I realised it rivalled us with another guild is there a way to reverse this? Cause I have everyone thinking we are going to "war". And I don't want us to be rivals with anyone forever. lol

**Comment by velddev** [comment]
You can change your rivals every day, I can maybe add a way to remove it, but it shouldn't make much of an impact whatsoever.

**Comment by willy7im** [comment]
how do i compare who higher. our guild or our rival?
