### ISSUE TITLE
Go-fish and memory games

### ISSUE THREAD

**Issue by julialol** [veldlabs/miki-bot#212]
I don't think I've seen a bot with Go-fish command. Like miki can DM you your hand and can choose a card like >spade 5 or >joker

**Comment by adv0catus** [comment]
For memory games, Miki could post a message with an X digit number and delete it after 1 second and you need to recall what the number was. There could be betting involved where getting it correct is 100% meko gain, getting 1 digit wrong is 50% meko gain and any more incorrect is void.

There could be a "Simon Says" type thing as well where perhaps Miki will do the same thing with the message but have a series of directions/instructions/keys that the user would need to remember. Miki could progressively increase difficulty with each successful round and the meko rewards would get progressively better, perhaps something like: x.05, x.10, x.25, x.50, x.75. x1, x1.10, etc. where it's additive.

ie, someone bets 100 mekos, they get +5 mekos, +10 mekos, +25 mekos, etc.

**Comment by julialol** [comment]
@adv0catus
There is a problem with the deleting, some people have logs and will cheat with that.
