### ISSUE TITLE
Achievement Achievements aren't triggering.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#214]
Have 11 achievements but still only have the 3 achievements achievement.

**Comment by velddev** [comment]
It checks once per achievement

**Comment by adv0catus** [comment]
I just got the 10k mekos cheevo and the pencil is still there. have 11, still shows the 3 cheevo achievement

**Comment by adv0catus** [comment]
This doesn't work when an existing achievement is "upgraded". I unlocked the level 50 achievement and I still have the pencil (3 achievement) achievement.

**Comment by velddev** [comment]
Odd. other people do get the achievement.
![](https://miki.is-a-good-waifu.com/23ab68.png)

**Comment by adv0catus** [comment]
![](https://i.imgur.com/QJSZ9jA.png)
![](https://i.imgur.com/fBU447m.png)
![](https://i.imgur.com/C0I0AKh.png)
