### ISSUE TITLE
">pet" command and action are different

### ISSUE THREAD

**Issue by kaw5150** [veldlabs/miki-bot#219]
For the " **> pet** " command, the response says that the " User **pats** person "; the command and action are different. I know it's small, but I just wanted to let you know. (:

**Comment by adv0catus** [comment]
It's just a quirk in how English works.

**Comment by kaw5150** [comment]
Technically "pet" and "pat" mean different things. They are similar actions, but they have different connotations. But I guess I could just be nit-picking.

**Comment by velddev** [comment]
This is because we used to have >pet and >pat, but they got merged.
