### ISSUE TITLE
Bug: >help <non-cmd> displays {0}

### ISSUE THREAD

**Issue by Pao-Lumu** [veldlabs/miki-bot#232]
Miki Version: Live (0.4)
Locale: All

Actions Taken:
`>help asdf`
`>help notacommand`
`>help <*anything that isn't a command*>`

Expected Behavior:
`This is not a command. To use >help [command] please fill in a existing command!`

Result:
`This is not a command. To use {0}help [command] please fill in a existing command!`

Probable cause:
Line 192 of Modules/[GeneralModule.cs](https://github.com/velddev/Miki/blob/master/Miki/Modules/GeneralModule.cs)
No format() is being applied to strings from L10N files.

**Comment by velddev** [comment]
You're absolutely right. The lines are still in need of implementation to the language files.

**Comment by velddev** [comment]
On a side note, very well explained bug report. thank you

**Comment by Pao-Lumu** [comment]
Bug has been resolved.
