### ISSUE TITLE
Miki doesn't respond to people sometimes

### ISSUE THREAD

**Issue by rosieneko** [veldlabs/miki-bot#24]
Currently Miki is not responding to people. Seems random. She will work otherwise.

Does not seem to be shard-related, but can't be sure about that one.

One particular user had the name "🙁 T O M I J U U 🙁". Miki was responding to their commands, but then suddenly stopped responding. With a name change to "T O M I J U U", Miki started responding to them again. She now responds to  "🙁 T O M I J U U 🙁" too.

Seems other people are having similar issues where Miki will not respond for a period, but start responding again. You've restarted shards so I'm not sure if that's the issue or not. Logging this since this is a recurring issue coming up in #support at the moment.

**Comment by velddev** [comment]
Either a accounts problem or miki was down for said shard
