### ISSUE TITLE
Suggestion: >fml

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#242]
Wouldn't be unique to Miki, but would be a command that brings it inline with most other bots. The functionality would be a random FML story. Not entirely sure how this would work, to be honest. Tried finding the FML API and it doesn't appear to exist officially, or it's behind some kind of wall. There was tonnes of hits for Github third party APIs, but didn't look into those.

**Comment by velddev** [comment]
The FMyLife api demands a 50/50 split.
