### ISSUE TITLE
Improvement: >roll - multiple different sided dice.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#246]
Allow for multiple dice to be rolled at once: `>roll {dice1} + {dice2} + {etc}`

Example:

>roll 2d2 + 4d4
Results: : rolled a 15. (3 (2+1) + 12 (3+3+2+4))

**Comment by davpfre** [comment]
Uhm... I don't know, whether you know... But this is already a feature. 
![image](https://user-images.githubusercontent.com/6499570/28570141-0b70ecf0-713d-11e7-8835-97d2f119d987.png)
I would take it a bit more chill with adding more feature suggestions, before checking if they exist already.

**Comment by adv0catus** [comment]
title should say multiple different sided dice then, if you need clarification

**Comment by davpfre** [comment]
The clarification is not for me. But thank you for clarifying.
