### ISSUE TITLE
Bug: >hatepasta/>lovepasta cannot be overwritten once chosen

### ISSUE THREAD

**Issue by Pao-Lumu** [veldlabs/miki-bot#250]
Miki Version: Live (0.4.0.1)

### Actions Taken:
`>hatepasta *pasta_name*`
`>lovepasta *pasta_name*`

#### After `>hatepasta`:
>Success!
>Your vote has been updated! Current Score: -1

#### After `>lovepasta`:
>Success!
>Your vote has been updated! Current Score: 1

#### After `>hatepasta`:
>Success!
>Your vote has been updated! Current Score: -1

#### After `>lovepasta`:
>Success!
>Your vote has been updated! Current Score: -1

### Probable Cause:
Likely something in [lines 402 to 413](https://github.com/velddev/Miki/blob/master/Miki/Modules/PastaModule.cs#L402) in PastaModule.

**Comment by velddev** [comment]
Confirmed bug.

![image](https://user-images.githubusercontent.com/13852840/28599001-8f6a11c0-71a7-11e7-88f6-e5a1e65495d8.png)

**Comment by velddev** [comment]
@IA-Xerise This is resolved. since commit b553c61
