### ISSUE TITLE
>ban sends a message even if the ban doesn't officially go through

### ISSUE THREAD

**Issue by bargy** [veldlabs/miki-bot#252]
![ban test](https://user-images.githubusercontent.com/24587911/28637310-6357847e-7241-11e7-8da2-632b62efb79a.png)
![bug 2](https://user-images.githubusercontent.com/24587911/28637311-668cf322-7241-11e7-9b06-bf70334cfc0e.jpg)

Basically I tried to ban a user above my rank in role hiearchy and the ban failed (of course), but the user still got the message.

**Comment by LovingMelody** [comment]
This occurs when Miki is below the person mentioned for ban.

**Comment by binn** [comment]
Let's close this issue, it's been fixed in PR #290
