### ISSUE TITLE
Music?

### ISSUE THREAD

**Issue by ThomasAunvik** [veldlabs/miki-bot#254]
As i just noticed in the Wiki FAQ i see that you will add Music when you reach 250$ a month.
![](http://i.imgur.com/pDWYH3x.png)
And now you have reached over 250$.
![](http://i.imgur.com/a8BPMC6.png)

If you are willingly, can you please tell the progress of the music commands?

**Comment by adv0catus** [comment]
It was decided that the community wants more functionality over music.

**Comment by ThomasAunvik** [comment]
I see. Thanks for the info.

**Comment by adv0catus** [comment]
![](https://i.imgur.com/8iYIqZ7.png)
