### ISSUE TITLE
Change reaction images that use Photobucket

### ISSUE THREAD

**Issue by davpfre** [veldlabs/miki-bot#257]
Some of the command's reaction images, use Photobucket. Which in it self, isn't a problem. If it wasn't for Photobucket being greedy and limiting 3rd party hosting.

An example from the cuddle command:
![image](https://user-images.githubusercontent.com/6499570/28745313-54daa3c2-7476-11e7-95bd-52f528e2eeb5.png)

**Comment by velddev** [comment]
That's pretty gay

**Comment by davpfre** [comment]
pls

**Comment by xialight** [comment]
Replaced image with a imgur link just now
