### ISSUE TITLE
Blackjack Takes mekos but doesn't let you play.

### ISSUE THREAD

**Issue by UzumeTennouboshi** [veldlabs/miki-bot#259]
When you do >blackjack # it takes the mekos you insert but doesn't do the game. lost 22k mekos. Refer to the ping in Miki Beta server to see.

**Comment by Thyoity** [comment]
Yeah, I just lost my >daily because of this... ;(
I have 0 mekos now. The only way out is to spam and gather some lvl up mekos.

**Comment by velddev** [comment]
This has been fixed
