### ISSUE TITLE
Removing Proposals

### ISSUE THREAD

**Issue by RileyWasHere** [veldlabs/miki-bot#260]
I have a lot of proposals that I can't remove because the person is no longer in any server of mine. What do I do?

**Comment by LovingMelody** [comment]
Please refer to the [wiki](https://github.com/velddev/miki/wiki/FAQ)

**Comment by McChantel** [comment]
This doesn't even help?? You can divorce people who've left the server but you can't decline their proposal.

**Comment by velddev** [comment]
You can remove all your proposals by doing `>declinemarriage *`

**Comment by McChantel** [comment]
Thanks so much!
