### ISSUE TITLE
Miki doesn't respond to Hit or stay after blackjack

### ISSUE THREAD

**Issue by Phanrazak** [veldlabs/miki-bot#261]
Only confirmed for Regular Miki. Patreon miki doesn't seemed to be affected
http://i.imgur.com/VeNxeAz.png

**Comment by vctorlj** [comment]
To add more info: when you try to start a new blackjack game after the first one doesn't respond Miki creates it, when she should said that you were in a game already.

**Comment by velddev** [comment]
@blueko it does this per channel.

**Comment by vctorlj** [comment]
@velddev well, I mean in the same channel as old game ofc.
