### ISSUE TITLE
Nsfw content not working

### ISSUE THREAD

**Issue by bumblebeeman101** [veldlabs/miki-bot#263]
For some reason the Nsfw commands are not working even on channels with nsfw enabled and i can't figure out if there is some sort of command that i need to put in for miki or if this is a glitch, please halp

**Comment by xialight** [comment]
Make sure that the name of channel starts with "nsfw-" such as "nsfw-samplename".

**Comment by bumblebeeman101** [comment]
thank you for telling me that, although that seems like an arbitrary requirement for channels i marked as nsfw already in discord but it works now so thank you
