### ISSUE TITLE
Miku blackjack doesn't let me treat two aces both as  aone

### ISSUE THREAD

**Issue by weso12** [veldlabs/miki-bot#264]
Basically when I was playing blackjack on discord I got a 6 and 4 plus two aces normal blackjack rules would say that I have 12 but the bot said I busted
![screen shot 2017-08-05 at 9 50 13 pm](https://user-images.githubusercontent.com/29314172/29000707-d1f761b2-7a28-11e7-8c16-32e5fdafe1c5.png)

**Comment by Phanrazak** [comment]
First off, it's Miki. She treats Aces as either 11 or 1

**Comment by weso12** [comment]
But here's the thing whenever i played another game it is willing to change an 11 to a 1 to prevent me from busting but it's not doing that with 2 aces, note that in this situation you could treat aces are either 11 or 1, if you treat them both as 1 I would not bust.

**Comment by Phanrazak** [comment]
Well, I don't know much about how it actually works, I'll keep this issue open and let veld explain it once he gets online

**Comment by adv0catus** [comment]
In Blackjack, Aces are treated as 11 and then 1 if that puts you over. Miki should be following the same rule and treat two Aces as 2, not 12 or 22.

**Comment by velddev** [comment]
this has been fixed.
