### ISSUE TITLE
A Couple of Marriage Bugs

### ISSUE THREAD

**Issue by xialight** [veldlabs/miki-bot#27]
Azumi#8379 (Discord ID: 114190551670194183) can marry duplicates. (There might be other cases)
![](https://images-ext-1.discordapp.net/eyJ1cmwiOiJodHRwOi8vaW1hZ2UucHJudHNjci5jb20vaW1hZ2UvODcxNTAxYTBmY2NhNDMxYzg0YWU0N2Y1MmQ0MTA4OGUucG5nIn0.as4gpWQO0H1o88Tptt8tzeZhC2g)
In addition, recently married people won't show on Azumi's profile
![](https://cdn.discordapp.com/attachments/249373403511914497/260577208551211018/unknown.png)
Furthermore, it affects the people Azumi are married to
![](https://cdn.discordapp.com/attachments/249373403511914497/260577370686226432/unknown.png)

**Comment by velddev** [comment]
This is fixed with marriage v2
