### ISSUE TITLE
Achievements gone

### ISSUE THREAD

**Issue by AlmightyFiji** [veldlabs/miki-bot#272]
So i just checked my profile and all my achievements where gone, and i can't get them back.
Before:
![screenshot 35](https://user-images.githubusercontent.com/30279185/29244008-6a092d88-7f73-11e7-9ada-4171c0112867.png)

Now:
![screenshot 34](https://user-images.githubusercontent.com/30279185/29244015-80ca6c26-7f73-11e7-85f7-a3d9525605c3.png)

**Comment by AlmightyFiji** [comment]
ah never-mind they're back

**Comment by velddev** [comment]
Consider joining the miki support server shown in `>info` to be up to date whenever something turns off for a while.
