### ISSUE TITLE
Edited Miki bot

### ISSUE THREAD

**Issue by ewof** [veldlabs/miki-bot#281]
i'm making an edited version of miki bot i'm not going to release it because well the bot isn't mine its velds i only edited it, iv'e finished my edits but i cant find the place where i put the bot id token etc could someone tell me what file these are in?

**Comment by velddev** [comment]
./miki/config.miki

**Comment by ewof** [comment]
i cant find ./miki/ do i have to build the sln file to get it

**Comment by velddev** [comment]
yes.
