### ISSUE TITLE
Offensive Pastas

### ISSUE THREAD

**Issue by moonbok** [veldlabs/miki-bot#287]
Is there a way we could report inappropriate pastas to you and you could delete them? Things like >pasta [n-word], >pasta alex, etc shouldn't be allowed to exist imo. >_>

**Comment by Phanrazak** [comment]
You can just pm any of Miki staffs with the name of the pasta. We can have veld to have it removed. Disclosing the names of the pastas in public might make people upset if we delete it. And also people can just recreate pastas if said pasta was deleted
