### ISSUE TITLE
>prune & >clean don't delete old messages.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#288]
In the screenshot below, I used both `>clean` and `>prune` without any variable and Miki didn't delete the message. I assume it has to do with the message being old, but I'm not sure what the cut-off point is. Perhaps it could be an API issue, I'm not sure.

![](https://i.imgur.com/xIeo6Fz.png)

**Comment by velddev** [comment]
this is a api thing. bots cannot delete messages older than 2 weeks.
