### ISSUE TITLE
The "Sorry, this command is still on cooldown for 6.19E-05 seconds!" 

### ISSUE THREAD

**Issue by IslaCarroll** [veldlabs/miki-bot#29]
This seems to happen every now and then, and then it stops responding to commands for a good couple of minutes.
It has happened many times with different commands, including the pasta command.
![sadfasdf](https://cloud.githubusercontent.com/assets/24777047/21482526/eaf357ba-cb29-11e6-9202-0290f8d4ea55.png)
I'm not a very good person with programming so I don't know if its just a timing thing or what

**Comment by Numailia** [comment]
solution: stop spamming miki commands

**Comment by velddev** [comment]
Might be fixed, I didn't use generic UTC time.
