### ISSUE TITLE
>give with no argument string error.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#292]
![](https://i.imgur.com/NZvpA6u.png)

**Comment by hmonhub** [comment]
It gives an error because you didn't use the right form. But iirr, the error message used to be more useful than this, like reminds people to do the right command.

**Comment by adv0catus** [comment]
That's why I made this issue ticket.

**Comment by Pao-Lumu** [comment]
Problem is [here](https://github.com/Mikibot/Miki/blob/master/Miki/Modules/Accounts/AccountsModule.cs#L449).
"give_error_no_arg" should be wrapped with an e.GetResource()

**Comment by adv0catus** [comment]
#https://github.com/Mikibot/Miki/pull/305
