### ISSUE TITLE
maxBet comparison

### ISSUE THREAD

**Issue by LovingMelody** [veldlabs/miki-bot#294]
https://github.com/Mikibot/Miki/blob/c45bbe5466c933b60666d3f3a2a667972b9f97bc/Miki/Modules/Gambling/GamesModule.cs#L478
This comparision should be on else ``if (bet > maxBet) ``

**Comment by Drummss** [comment]
I did a special update to change it from ">" to ">=" previously on purpose 🤔

**Comment by velddev** [comment]
Agreed.

**Comment by Drummss** [comment]
Fair enough then.

**Comment by Drummss** [comment]
Changed :)
