### ISSUE TITLE
>marry / >divorce issues

### ISSUE THREAD

**Issue by rosieneko** [veldlabs/miki-bot#3]
This was documented already, but JUST in case, recording down some more.

> divorce used by person A removes marriage from person B's profile, but leaves it on person A's profile. 

Person B, after person A divorces, cannot use >divorce on person A because they are technically not married anymore.

Person A then cannot marry person B because it's already on their profile, HOWEVER person B can marry person A, and then the marriage appears again on person A's profile.

**Solution to this:** Make sure >divorce wipes the data for the marriage from both people's profiles.

**Comment by velddev** [comment]
It _should_ be doing this. I'll check it out

**Comment by velddev** [comment]
fixed in 1.8.1
