### ISSUE TITLE
>lb is wrong.

### ISSUE THREAD

**Issue by TheHawker128** [veldlabs/miki-bot#312]
Leaderboards returning incorrect results. Says I am #377 globally but not on the leaderboard.
![awgwsg](https://user-images.githubusercontent.com/32230056/30777619-aeef8f96-a0b6-11e7-8c8f-39cda70ca876.JPG)
![sgr](https://user-images.githubusercontent.com/32230056/30777620-aef42114-a0b6-11e7-9d65-64d93340cd8f.JPG)

**Comment by adv0catus** [comment]
Page numbers are wrong, too.

**Comment by adv0catus** [comment]
Also, you can look up negative pages.
