### ISSUE TITLE
>rep has no limit

### ISSUE THREAD

**Issue by ghost** [veldlabs/miki-bot#313]
I've noticed when I gave someone a reputation point, I suddenly had -1 point. This was indeed funny so we all kinda messed up. 
![schermafbeelding 2017-09-24 om 23 57 21](https://user-images.githubusercontent.com/15174461/30787208-02d46d16-a184-11e7-94dc-ad24a68414a6.png)
![schermafbeelding 2017-09-24 om 23 55 42](https://user-images.githubusercontent.com/15174461/30787209-06b594e6-a184-11e7-8eb1-68f2d2bdad96.png)

**Comment by Phanrazak** [comment]
Fixed
