### ISSUE TITLE
Rigged

### ISSUE THREAD

**Issue by ghost** [veldlabs/miki-bot#315]
I thought coinflip was 50/50 but I was apparently wrong
![schermafbeelding 2017-09-30 om 01 32 41](https://user-images.githubusercontent.com/15174461/31039622-576b165a-a57f-11e7-9941-d014af075854.png)
![schermafbeelding 2017-09-30 om 01 32 47](https://user-images.githubusercontent.com/15174461/31039621-576a777c-a57f-11e7-9cb6-2097d28de790.png)
![schermafbeelding 2017-09-30 om 01 32 36](https://user-images.githubusercontent.com/15174461/31039624-576e6e90-a57f-11e7-90db-a87cc3a3f176.png)
![schermafbeelding 2017-09-30 om 01 32 30](https://user-images.githubusercontent.com/15174461/31039623-576c3e22-a57f-11e7-8524-568ce770b01e.png)

**Comment by adv0catus** [comment]
Miki is open source. Feel free to read the code for yourself.

**Comment by velddev** [comment]
Yep. All the code is completely visible on the code tab of this website.
