### ISSUE TITLE
how do you delete users who have left the server, from the local leaderboard?

### ISSUE THREAD

**Issue by sash23** [veldlabs/miki-bot#321]

**Comment by adv0catus** [comment]
You don’t. They participated in that guild so they’re associated with the local leaderboard.

However, I have made a suggestion on the Miki support server in the #suggestions channel to create a command that will allow guild administrators to purge the local leaderboard of users that have left every 24 hours.

**Comment by velddev** [comment]
I'll look into this whenever I can
