### ISSUE TITLE
>rep @<self> <all|#> claims success

### ISSUE THREAD

**Issue by Pao-Lumu** [veldlabs/miki-bot#322]
Self-tagging with >rep will succeed regardless of rep transfer success or failure

### Actions taken:
`>rep @TheGrammarJew#9410`
`>rep @TheGrammarJew#9410 all`
`>rep @TheGrammarJew#9410 1`
`>rep @TheGrammarJew#9410 2`
`>rep @TheGrammarJew#9410 3`
`>rep @TheGrammarJew#9410 1000`

### Observed behavior: 
No rep transferred
All commands returned
![2017-10-19 14_27_42- miki_test](https://user-images.githubusercontent.com/8527287/31790051-c6e0c0fc-b4d9-11e7-8758-c3c40c538c50.png)

### Expected behavior:
No rep transferred
An error message ~which I would picture if I could get it to show up.~

### Associated files:
[AccountsModule.cs](https://github.com/Mikibot/Miki/blob/master/Miki/Modules/Accounts/AccountsModule.cs)

### Notes:
Error check was accidentally removed with a previous commit.
[See deleted line 338](https://github.com/Mikibot/Miki/commit/3099b79f02cb217817b059136fd9974068f3e930#diff-24b5ae63903938afcdd3fb5c3d60d62aL338)

**Comment by velddev** [comment]
On it!

**Comment by velddev** [comment]
Fixed this in d1b16ea
![](https://i.imgur.com/MBESUol.png)

**Comment by Pao-Lumu** [comment]
Sweet! Thanks Veld!
