### ISSUE TITLE
allow nsfw commands to run in any channel marked as a nsfw channel

### ISSUE THREAD

**Issue by zfbx** [veldlabs/miki-bot#329]
nsfw commands rule34, e621, yandere and gelbooru only work if a channel is named "nsfw" but I want my channel to be called other things like "hentai" or run the commands in other channels reguardless of their name.. could you make it where these commands will work in any channel that has the nsfw property on the channel itself rather than by its name?

**Comment by adv0catus** [comment]
Discord API doesn't support this.

**Comment by adv0catus** [comment]
Also, please make suggestions in the #suggestions channel on the official Miki support server: https://discord.gg/veUGD9t

**Comment by zfbx** [comment]
the C# api doesn't? cause I know for sure Discord supports this because discord.js supports `message.channel.nsfw` returning a boolean

**Comment by zfbx** [comment]
I don't really consider this a suggestion as much as a bug.. even causes confusion for people wondering why the command doesn't work cause it doesn't give any feedback like "rename the channel to nsfw" or something.

**Comment by velddev** [comment]
Hey zfbTony,

You are indeed right. This is a library related issue. They have a fix for 1.0.3, however, I do not like to have unreleased libraries in production. Hope you agree with me on that :)

This is definitely an issue and not a suggestion. I'll look into when the update releases!

**Comment by velddev** [comment]
Hey, 

this fix has been implemented in the latest git commit and will be shipped in miki 0.6
