### ISSUE TITLE
Weird reminder behaviour

### ISSUE THREAD

**Issue by purple-ice** [veldlabs/miki-bot#330]
Any characters that follow the specified time, make the bot instantly remind you whatever you wanted it to.

I noticed this only because I simply put a full stop after it.

Can be reproduced by writing literally anything after specifying time, and I think that this should be fixed.

Example:
>\>remind Do something in 10 hours.
Bot response: "I'll remind you to **Do something** in **", DM's you the reminder straight away.

Can be fixed by checking whether a string that is expected to be time unit *starts* with said unit instead of checking whether it *is* said unit.

**Comment by velddev** [comment]
I'll look into this

**Comment by Drummss** [comment]
It's because it does a direct comparison with the various time strings instead of using .Contains(). Updating it would require editing Meru's source. Remind API would be a better solution though :D

**Comment by velddev** [comment]
This issue has been solved in this [commit](https://github.com/Mikibot/Miki.Framework/commit/f81c7200d7f98f4c7ee2cd0b562bde824efbd8e0)

Proof: ![](https://i.imgur.com/Kgn0luZ.png)

**Comment by purple-ice** [comment]
Thanks :)

It's nothing breaking but sometimes annoying.

**Comment by velddev** [comment]
Got to keep up the quality in miki 👍
