### ISSUE TITLE
Marriage is 7 kinds of fucked up

### ISSUE THREAD

**Issue by bargy** [veldlabs/miki-bot#34]
1: the person that proposes to someone seems to be the only one that can terminate the proposal. The person that you ask cannot decline properly because it just says "this person has not proposed to you"

2: PROPOSALS DON'T AUTO CANCEL. I have proposed to a person this morning and another one proposed me and I can't initiate any more marriages because _those are still around VELD_

3: order is in order of proposal when you have multiple people

For the 4th issue, please see the attached item
![discord_2016-12-31_18-12-17](https://cloud.githubusercontent.com/assets/24587911/21578548/d06b3da4-cf84-11e6-800e-912b57e146c6.jpg)

**Comment by bargy** [comment]
To add to number 2: proposals seem to time out, but the proposal itself keeps lingering. So unless you do something, I can't get to 5 marriages.

**Comment by bargy** [comment]
Apparently number 5 cropped up: according to user Azumi, he/she never accepted a marriage and he/she is still married to someone.
http://i.imgur.com/9dYyxs3.jpg

**Comment by IA-Xerise** [comment]
All these issues besides: 
![image](https://cloud.githubusercontent.com/assets/24828421/22865769/9e41892a-f138-11e6-9f3a-7c5118ff4b53.png)
have been fixed Afaik.
Marriage slots are meant to stay at 3 from now on with the option of buying more with mekos when Veld adds the command.
