### ISSUE TITLE
User getting no exp

### ISSUE THREAD

**Issue by DasVampy** [veldlabs/miki-bot#340]
The user Senpai Kozan#1665  is not getting experience

![oof](https://user-images.githubusercontent.com/33581221/32692742-01a65426-c71e-11e7-933f-d5c7bf2bd762.png)

but can use other Miki commands

![nani](https://user-images.githubusercontent.com/33581221/32692767-68ac3672-c71e-11e7-8186-36d47ccec63c.png)

**Comment by velddev** [comment]
Should be fixed with a restart

**Comment by DasVampy** [comment]
restart fixed it, thanks
