### ISSUE TITLE
Divorce won't notice a name with an emoji

### ISSUE THREAD

**Issue by Phanrazak** [veldlabs/miki-bot#351]
When doing manual divorce, Miki doesn't recognize a name that ends with an emoji, Needs further testing to test if it work with other name variations. Currently only 1 report

**Comment by Pao-Lumu** [comment]
This looks like it's probably down to spaces.

If the name is `:thinking::thinking:` (no space between the second and third colons), `>divorce :thinking: :thinking:`(w/ a space) will fail.

**Comment by Phanrazak** [comment]
Already tried with times with or without spacing and with and without backslashes to turn it into traditional Unicode. But it didn't work

**Comment by Phanrazak** [comment]
https://i.imgur.com/k7qzB0k.gifv Have tried and it doesn't seems to work. Refer to gif for demo

**Comment by Pao-Lumu** [comment]
Boaty McBoatFace's profile didn't say they were married to Phan or Naganami.

![discord](https://user-images.githubusercontent.com/8527287/33589596-2377ef78-d93f-11e7-934c-cebb3ffb6b88.png)

Succeeds with my tests. Both with `:thinking:` and actually copying the emoji.

**Comment by Pao-Lumu** [comment]
Bump, still cannot reproduce this issue.

**Comment by Phanrazak** [comment]
Well, there's no reason to still have it as an issue if it's not really a problem. I'll just close it

**Comment by velddev** [comment]
I think I know what it is, keep it open please

**Comment by Pao-Lumu** [comment]
@velddev From [the gif](https://imgur.com/k7qzB0k) Phan shared
![youcantdivorcewhatyouarentmarriedto](https://user-images.githubusercontent.com/8527287/34123628-c9e38bf4-e3f5-11e7-9e0a-2b09be2fc85d.jpg)

Unless this is on an alternate account named IA or Ayana, Boaty is not married to Phan, thus the error is correct and there is no bug.

**Comment by Markieyer** [comment]
If I were to say something, then here, I'm the one with this error, and it's still a huge bother, 
![screenshot_20171225-192621](https://user-images.githubusercontent.com/34459231/34344329-87852a32-e9aa-11e7-9b9c-00bacf35a74c.jpg)
That's the person I cannot divorce, I've tried :heart: :hearts: and a couple others in multiple ways, nothing works to divorce them, so.

**Comment by marcosgb1** [comment]
how to divorce someone have deleted ur discord account? not working for me to divorce T_T

**Comment by velddev** [comment]
You can still use their name in >profile @marcosgb1

**Comment by Pao-Lumu** [comment]
Any word on this? I couldn't/can't reproduce this.

**Comment by velddev** [comment]
I haven't yet checked this issue, but I did rewrite the marriage/divorce pipeline. I'll leave it open until we know for sure.

**Comment by Pao-Lumu** [comment]
I'll give it a try later.

**Comment by PapaSmurf-ML64** [comment]
I am also experiencing this issue upon attempting to divorce someone no longer on the server with an emoji in front of their name, almost seems like the bot ignores the command. I've tried the name as shown in my profile, their actual Discord username and #, with and without spaces, etc., all to no avail.

**Comment by adv0catus** [comment]
With the new divorce flow, even if it's not currently working, this issue is resolved.
