### ISSUE TITLE
Profile experience bar always almost full.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#353]
It’s supposed to represent the progress towards the next level, right? I just levelled up and the progress bar is almost full still.

![](https://i.imgur.com/k2jjPjU.png)

**Comment by Phanrazak** [comment]
As far as I'm concern, it shows your current progress from start to the next level, not your progress from 1 level to another. In other words. It takes into account all your exp right down to the first one

**Comment by adv0catus** [comment]
That kind of defeats the purpose, then. After a few levels, it’ll just always be almost full
