### ISSUE TITLE
Miki Blackjack AI Bug

### ISSUE THREAD

**Issue by scarman12158** [veldlabs/miki-bot#356]
Miki's AI hit on 21... twice
![miki bug](https://user-images.githubusercontent.com/34201908/33522053-f85cbf92-d7b0-11e7-8985-dc7a8fe5ffb3.png)

**Comment by adv0catus** [comment]
Seems to me like Miki is getting confused due to the Five Card Charlie rule.

**Comment by velddev** [comment]
Yep. This is just blackjack rule.
https://wizardofodds.com/games/blackjack/strategy/charlie/ for more information

**Comment by Pao-Lumu** [comment]
A friend of mine has this happen and gained 77 mekos instead of his bet 100. Is that also part of the rule? I'm not familiar with blackjack's rules.
