### ISSUE TITLE
Black Jack Issue

### ISSUE THREAD

**Issue by iscoulter** [veldlabs/miki-bot#357]
It seems when Miki runs Black Jack that she does not continue to hit when she is below 15. This is either just a rule forgotten to be implemented or because I had a lower number than her at the initial draw that the program didn't continue to hit. 

Sequence of events:
Player -> 4 and Q || Miki -> 5 and ?
Player -> Stay
Miki - > 5 and K
Miki Wins!

In Black Jack the dealer is required to play until they have 17+ for a score which means Miki should have hit and received another card possibly causing a "Bust"

**Comment by OfficialAudite** [comment]
Realized that too when I use it. But thought that it was intended to be that.

**Comment by LovingMelody** [comment]
I'll look into fixing this.

**Comment by iscoulter** [comment]
<3

**Comment by velddev** [comment]
This has been fixed in 0.6.1 release.
