### ISSUE TITLE
Profile Not Being Created

### ISSUE THREAD

**Issue by ravendalll** [veldlabs/miki-bot#358]
Randomly people will try and use the bot and it says they won't have a profile. Using the command >profile or >daily just pulls up an error message.

![daily not working](https://user-images.githubusercontent.com/34349954/33731413-04e52cc4-db51-11e7-9e8e-f17c53d8ac96.png)
![profile not working](https://user-images.githubusercontent.com/34349954/33731414-05816076-db51-11e7-827d-68b42b6d89ca.png)

**Comment by Phanrazak** [comment]
They have to have some experience first. Try letting them talk first
