### ISSUE TITLE
>give is broken.

### ISSUE THREAD

**Issue by LoloTheLoloser** [veldlabs/miki-bot#36]
I'm pretty sure this is known but >give is broken.

As you can see here,
![bls](https://cloud.githubusercontent.com/assets/24811244/21622922/df9c6c62-d24f-11e6-8668-1fac1330d2d8.PNG)
![blss](https://cloud.githubusercontent.com/assets/24811244/21622923/df9cebd8-d24f-11e6-84f8-35842ea0c995.PNG)
![blsss](https://cloud.githubusercontent.com/assets/24811244/21622924/dfa12004-d24f-11e6-85ac-ec8b21797932.PNG)

I don't know why this happens but I can assure you that isn't suppose to happen...

**Comment by LoloTheLoloser** [comment]
I just realised the images aren't in order.

**Comment by Numailia** [comment]
(this is a really bad example because I only had 500 to begin with :^) )

**Comment by velddev** [comment]
I'm confused because of this. But i'm sure it's been fixed by now.
