### ISSUE TITLE
Blackjack freezes if you get 21 from the start

### ISSUE THREAD

**Issue by ghost** [veldlabs/miki-bot#360]
Hi, i don't know if there's a command to reset blackjack in a channel, but I did >bj 50 in my general chat, and I got 21 instantly. I said stay of course, but it didn't do anything. Then I tried hit, and it didn't do anything either. The bot is stuck here and it won't let us play another game in this channel.

**Comment by Phanrazak** [comment]
I tried recreating the situation but came out [differently](https://i.imgur.com/yj4G67m.png) Make sure Miki has the correct permissions such as the ability to edit messages. And not just Admin access

**Comment by ghost** [comment]
hi Phanrazak, you are right, I had to add even more permissions to miki bot.

i didn't think i needed to because she works doing >bj and all other commands until when it gets stuck, so i didn't think that was the issue. it works now!

**Comment by Phanrazak** [comment]
Feel free to use this [invite ](https://discordapp.com/oauth2/authorize?&client_id=160185389313818624&scope=bot&permissions=355593334) that has the correct perms for her if you have any other trouble resetting it up. And join the support server if you have other questions that needs quick answers. Just use the info command for miki
