### ISSUE TITLE
haiya, making a server with the help of Miki :3

### ISSUE THREAD

**Issue by Duztey** [veldlabs/miki-bot#361]
So uh, i really like the way you can do the >setrolelevel command, although, how do i know that it works, cause Miki does not respond when i put in what kind of level i want the role to be for. I put in this:  >setrolelevel <5> <Lesser Spirit> but i do not get any respond from Miki, also no one in my server can level up typing long messages either. ;_; I DONT UNDERSTAND ;_; pls help

**Comment by LovingMelody** [comment]
Hi, its `>setrolelevel <role> <level>` sorry for the confusion
