### ISSUE TITLE
Account with no marriages using buymarriageslot command gains mekos

### ISSUE THREAD

**Issue by Schingiuire** [veldlabs/miki-bot#363]
I had a member who did not have any marriages use the 'buymarriageslot' command and miki gave a message asking if the user wanted to buy a marriage slot for -10000. When the member accepted, Miki gave them 10000 mekos. The user was able to repeat this process several times with Miki using increasingly lower numbers and giving the negative amount to the user each time. Once she reached 0 mekos, she began deducting mekos.

**Comment by velddev** [comment]
Fixed.
