### ISSUE TITLE
Blackjack Unresponsive

### ISSUE THREAD

**Issue by kinononn** [veldlabs/miki-bot#365]
While i was playing Blackjack someone started a game while i was playing, and i tried to >hit for my game, and it was unresponsive. After the other person's game as well, it fails to respond and i'm not sure how to fix it? I try to start a new game, but it informs me that I'm still in game.  Is there a way to resume or force end the game?

**Comment by kinononn** [comment]
it somehow fixed itself? After like 30 minutes.

**Comment by velddev** [comment]
The correct usage is `hit`, without the prefix
