### ISSUE TITLE
Black Jack Unresponsive

### ISSUE THREAD

**Issue by kinononn** [veldlabs/miki-bot#366]
I just had a problem and i thought it was fixed, but now Miki is completely unresponsive when playing Black Jack and not just to me. She will start a game and then wont respond after you try to >hit or >stay. (I already lost 200 mekos trying to figure out whats happening...). Is there a way to fix this? Is it a bug or is she broken? We tried kicking her and inviting her back in just to see if it'll work, but she still wont respond.

**Comment by velddev** [comment]
Check my response on #365
