### ISSUE TITLE
Setting Role Levels Doesn't work

### ISSUE THREAD

**Issue by kitalizer** [veldlabs/miki-bot#367]
When ever I try to add role based on people levels it does nothing? no message pops up after I do the command >setrolelevel 1 Grunt but no one changes? and even when I made a level 2 role no one changed.

**Comment by Phanrazak** [comment]
Experience having issues. It's been disabled until miki 1.0 is released

**Comment by velddev** [comment]
This has been fixed with the role management rewrite in `0.6`. Coming when it's ready.
