### ISSUE TITLE
Problems With nsfw commands

### ISSUE THREAD

**Issue by superdolphinman** [veldlabs/miki-bot#368]

**Comment by superdolphinman** [comment]
Woops didnt put description. Anyways got the bot in the server and all commands work but those. Went into a nsfw channel and as usual the commands functioned normally and even went to setting her role to having no problems with accessing the server and all that but still no response from miki whenever the command is issued. Any solutions?

**Comment by Phanrazak** [comment]
Consider joining the discord to inquire about this. There's a faq that you can check out that should answer some questions https://discord.gg/veUGD9t
