### ISSUE TITLE
Can't cancel/delete a proposal?

### ISSUE THREAD

**Issue by izzyrng** [veldlabs/miki-bot#369]
>marry command works fine but I can't find out how to get rid of my proposal if someone is inactive or if they don't decide to accept or decline it

**Comment by velddev** [comment]
You can use `>declinemarriage *` to remove your proposals sent

**Comment by izzyrng** [comment]
That didn't clear them when I type >showproposals, under Proposals sent I still see them. Does it take a while to update?

**Comment by velddev** [comment]
It shouldn't, maybe there was a porting bug. you can also try `>declinemarriage [their name]` if you received it.

**Comment by izzyrng** [comment]
![image](https://user-images.githubusercontent.com/35549253/35076736-d7972d0c-fbc7-11e7-982d-2e9fccfa599c.png)
this is what I see after i used the command to clear as shown 
![image](https://user-images.githubusercontent.com/35549253/35076754-e7b74550-fbc7-11e7-81a8-1864fbef7ceb.png)

**Comment by velddev** [comment]
Odd, I'll make sure to make this possible soon.

**Comment by izzyrng** [comment]
Thank you

**Comment by velddev** [comment]
Should be fixed :)
