### ISSUE TITLE
XP count not updating

### ISSUE THREAD

**Issue by Numailia** [veldlabs/miki-bot#37]
Each user's XP count used to be updated once per ~5 secs, now it isn't updating at all

This user should be several levels higher by now (and also still has that nickname bug somehow):
![image](https://cloud.githubusercontent.com/assets/18292514/21622895/ccb15af4-d1cd-11e6-8252-ff2bf999b7a2.png)

![image](https://cloud.githubusercontent.com/assets/18292514/21623010/5cd5a888-d1ce-11e6-94be-b550a0a56294.png)

**Comment by velddev** [comment]
Fixed.
