### ISSUE TITLE
Leaderboards Naming Bug When They Have Same Mekos

### ISSUE THREAD

**Issue by xialight** [veldlabs/miki-bot#370]
Velj have the same mekos as Snipefrost. Their names are both synced. However, Snipefrost replaces Velj on leaderboards.
![](https://i.imgur.com/x1BpbXf.png)
![](https://i.imgur.com/zvWEO3p.png)

**Comment by velddev** [comment]
This is not a bug, this is a priority thing where they sort a secondary column, Techically they share the spot.
