### ISSUE TITLE
profile name is not the same as my own.

### ISSUE THREAD

**Issue by kenlyshino** [veldlabs/miki-bot#38]
i have changed my name at least over a week ago, but it still shows my old profile name.

**Comment by kenlyshino** [comment]
![screenshot 147](https://cloud.githubusercontent.com/assets/24908450/21632364/a4d4b8e6-d213-11e6-9f8a-539eff2d5465.png)
as you can see, my name is currently ♥Kenlee♥.

**Comment by velddev** [comment]
Please check again now.

**Comment by kenlyshino** [comment]
still not fixed.

**Comment by velddev** [comment]
Is Kenlee a nickname?

**Comment by kenlyshino** [comment]
no.

**Comment by kenlyshino** [comment]
i changed my name to: ♥Miya♥#7578 now. But it still shows the same

**Comment by velddev** [comment]
This should be fixed in the new 0.1.9.9

**Comment by kenlyshino** [comment]
nope.

**Comment by IA-Xerise** [comment]
Still not fixed afaik.

**Comment by Jun6587** [comment]
Same thing with me
