### ISSUE TITLE
Local Leaderboard for exp won't work

### ISSUE THREAD

**Issue by jodiewodie** [veldlabs/miki-bot#380]
**What went wrong?**
>leaderboards local
>leaderboards exp local
>lb local

This is entered and nothing is triggered to make miki respond.
This may be an issue with the discord server I am specifically in.

**How do I reproduce this issue?**
>leaderboards local
>leaderboards exp local
>lb local

**Comment by xialight** [comment]
Should be fixed now so I'm closing the issue.
