### ISSUE TITLE
Leaderboard pages wrongly indexed.

### ISSUE THREAD

**Issue by davpfre** [veldlabs/miki-bot#381]
Typing `>lb 0` returns the first page and `>lb 1` returns the second page. 

![image](https://user-images.githubusercontent.com/6499570/37337470-b002f376-26b4-11e8-8290-2c64727f10e7.png)

**Comment by xialight** [comment]
`>lb 1` should return the first page now, `>lb 2` should return second page and so forth. Since this is resolved, i'm going to close this issue.
