### ISSUE TITLE
Blackjack hit/stay not working

### ISSUE THREAD

**Issue by T0fuchunks** [veldlabs/miki-bot#382]
**What went wrong?**
After inputting the command for blackjack along with the amount of mekos, Miki put up the text for the game but neither hit nor stay would change anything. No new blackjack games could be started by the same user on the same channel (although the same issue pertained in other channels of the same server if a blackjack game was started there) and the mekos were essentially lost. Even after putting in miki.prefix > and being able to start a new blackjack game on the same channel, Miki still wouldn't respond to hit or stay for the new game. 

**How do I reproduce this issue?**
I'm not entirely too sure what brought this about but it may have been another bot's command for pruning messages shortly before Miki put up the blackjack text that interfered with it? Again, not entirely too sure what had happened.

**Comment by velddev** [comment]
Make sure you didn't try `>hit` or `>stay`, as said in the command, you type just `hit` or `stay.

**Comment by T0fuchunks** [comment]
hit and/or stay was what was typed after the initial >blackjack command but neither would have an effect

**Comment by adv0catus** [comment]
Miki has permissions to manage messages, right?

**Comment by T0fuchunks** [comment]
Oh that was it. Thank you!
