### ISSUE TITLE
Miki Bot divorced first person in my marriage list.

### ISSUE THREAD

**Issue by luncee** [veldlabs/miki-bot#383]
I only typed in ">divorce" without putting a tag or anything and miki bot said I divorced someone i wasn't even married to? I then checked >profile and saw that the first person I was married to since august wasn't there anymore, I did it again and it removed the first person from the list again. I'm pretty sure this isn't supposed to happen, as I've done this before and nothing ever happened. (also if could get the marriage back (with it being at the top and with the same date) it would be nice hhh)

**Comment by velddev** [comment]
Odd, I'll take a look into this.

**Comment by Staphany** [comment]
Same thing happened to me, lost my marriage from October

**Comment by velddev** [comment]
Should be resolved, sorry for the inconvenience
