### ISSUE TITLE
reputation points

### ISSUE THREAD

**Issue by trick4ndTreat** [veldlabs/miki-bot#384]
**What went wrong?**
the reputation point reset system seems to have busted

**How do I reproduce this issue?**
i have given reputation to 3 people and i checked via >rep once again and it said that it has 23 hours til it resets. 
However, in the next day, the reset timer still written has 23 hours; with few minutes differences, but no reputation has been sent since the day before. I have checked the timer before then and it did go down as i recalled that it said it had 3 hours, and 15 minutes left before it resets. however it went back to 23 hour again, with 0 reputations to give out.

**Comment by velddev** [comment]
Should be resolved

**Comment by itsboringwithoutyou** [comment]
🚶
