### ISSUE TITLE
Miki won't allow me to marry

### ISSUE THREAD

**Issue by ghost** [veldlabs/miki-bot#386]
I wanted to marry someone, and so I did the marry command.
They tried to accept (a few seconds later), but it said "this person hasn't proposed to you!"
But then, they declined, and it worked, it's super confusing.

Try to marry someone, and let them type the command to accept. She'll say you haven't proposed. Then let them to decline it, and Miki will show that it's declined.

I tried it the other way around, as well. I let my friend propose to me and the same thing happened.
Some screenshots to show --

**When I proposed:**
![3](https://user-images.githubusercontent.com/34387343/37493929-b2b73534-2874-11e8-8dad-ecf7b88bf45c.png)
![4](https://user-images.githubusercontent.com/34387343/37493930-b2cebccc-2874-11e8-868b-0f031441f1ee.png)

**When they proposed:**
![1](https://user-images.githubusercontent.com/34387343/37493936-bb0bad78-2874-11e8-8a16-737ff685e2af.png)
![2](https://user-images.githubusercontent.com/34387343/37493937-bb2169ba-2874-11e8-937d-241a355b9e9d.png)

I am married to someone else, but i've seen that Miki allows you to marry multiple people at a time (thank you for that feature by the way!)
I do love the bot a lot, I hope I can fix this.
Thank you!

**Comment by velddev** [comment]
This should been resolved :)

**Comment by ghost** [comment]
Thank you so much, it worked <3!
