### ISSUE TITLE
>Syncname Broke

### ISSUE THREAD

**Issue by Sworduster** [veldlabs/miki-bot#387]
**What went wrong?**
Atm my username =/= synced name in miki =/= name that apear in marriage lists

**How do I reproduce this issue?**

any old or new marriage will ref to a name i dont use anymore. and they cant divorce using that name in profile

**Comment by adv0catus** [comment]
The code is commented out; there's a known issue with the command.

https://github.com/Mikibot/Miki/blob/master/Miki/Modules/Accounts/AccountsModule.cs#L478
https://trello.com/c/RNeYLvtS/184-rework-syncavatar

**Comment by velddev** [comment]
Syncname has a new caching layer. The problem has been resolved, but not live.

**Comment by rasheequa** [comment]
I have the same problem

**Comment by adv0catus** [comment]
This works now.

**Comment by rasheequa** [comment]
no it still does not work (for marriage list)

**Comment by velddev** [comment]
User's namecache did not synchronize well. as it has it's own layer.

**Comment by Archun3935** [comment]
does it work now??

**Comment by adv0catus** [comment]
Not yet, check here for updates changelog: https://blog.miki.ai/

**Comment by adv0catus** [comment]
It looks like `>syncname` is functioning correctly, including marriage name on `>profile`.
