### ISSUE TITLE
Mekos Transfering

### ISSUE THREAD

**Issue by IrishhhHere** [veldlabs/miki-bot#388]
**What went wrong?**
Hi there, I am contacting you about your bot Miki. I am messaging you on behalf of a friend whos account got deactivated/delete for a currently unknown reason, I am currently talking to Discord's support team about transferring server ownership to my friends new account because she has a (what I would count as) big public server, it is going go so far, as well transfering any data that might be there such as friends or servers my friend is in. The reason for messaging you is my friend is wondering if she can get her Mekos transferred to her new account. 

**How do I reproduce this issue?**
Transfering my friend's Mekos on the inactive account to the active account.

Inactive account: MaayanSG#9604
Inactive account ID: 258737946109149184
New account: MaayanSG#7171
New account ID: 395980165613879306

My account: MyNameIzDylan#3935
My account ID: 163041748837203969

**Comment by Pao-Lumu** [comment]
I don't personally have a solution, but I can point you to the main Miki server.
https://discord.gg/55sAjsW
Ask in the support channel, they might be able to help you.

Good luck!
