### ISSUE TITLE
Miki Bet Limit suggestion 

### ISSUE THREAD

**Issue by Eldackar** [veldlabs/miki-bot#390]
I would like to make a suggestion to enhance Miki.

Could it be possible to increase the bet limit for games?

Actually it's 1 million for blakjack and 100k for slots and sometimes it could be hard to plan a strategy because of those limits.

Cordially,

**Comment by adv0catus** [comment]
There were tens of thousands of instances of each type of gambling game "played" to determine win ratios and balance. The limits are a result of that information to create a fair and balanced game in consideration of the overall mekos economy.

The limits may seem silly and arbitrary, but a lot of work and thought has gone into them. As a result, I can't speak definitely, I can't see them being changed any time soon.

**Comment by velddev** [comment]
Bet limits are made to make sure the economy doesn't fluxuate to too much mekos. This is a goal that isn't completely going well, but it's making progress.
