### ISSUE TITLE
Blackjack won't initiate when bet confirm w/o manage messages perm

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#395]
**What went wrong?**

Miki won't initiate the black jack game session when a bet confirmation is needed and Miki does not have the manage messages permission.

**How do I reproduce this issue?**

Initiate a black jack game session over the bet confirmation amount when Miki does not have the manage messages permission enabled.

---

Reported second hand through #main on the Miki support Discord server.

**Comment by Sworduster** [comment]
i suggest some error messages for this kind of issues

**Comment by adv0catus** [comment]
I'm going to assume this has been fixed but can't test to confirm.
