### ISSUE TITLE
Improving Miki Power

### ISSUE THREAD

**Issue by ghost** [veldlabs/miki-bot#396]
**Ideas to make a better Miki Bot**
Miki Bot is great giving us the ability to use actions. 

**Regarding roles...**
1.Allow Miki bot to auto assign role to new members. (In addition to removing this command) 
2.Allow Miki bot to allow individuals to assign a role to themselves. (In addition to removing this command)
3. Keep the ability to buy roles for x period of time or forever for a one time fee. (Ability to remove these options and roles) 

**Regarding welcome messages or goodbye messages...**
1.Give admins the ability to set a certain channel where announcements of any kind can be made. 
(For example, I would like all my welcome and goodbye messages to be made in my #announcement channel instead of my #rules channel.)

**Regarding NSFW content...**
1.Increase more NSFW sources, content, and commands. 
2.Allow bot admins to enable or disable permission to display content in certain channels. 

**Regarding economy...**
Miki bot seems to have a small scale economy in it, and it should be further expanded. 
1.Give bot admins the ability to adjust how much $ per message members receive and allow for a cooldown per $ given. (Example, $10 per message after 5 second cooldown) 
2.Give bot admins the ability to give $ per hour or day to assigned roles. (Example, Admins get $1000 per day, moderators get $950 per day, new member get $10 per hour)
3.Allow bot admins to set a set starting balance for everyone. 
4.Give bot admins the ability to lock and unlock certain channels from earning money for chatting.
5.Allow a member to be able to give money to another member.
6. Allow members to check their balance.
7. Allow bot admins to reset the server economy. (Everyone starts at $0 again)
8. Allow bot admins to reset all the economy settings back to default. 
9. Allow bot admins to change the name of their currency and the currency display. (Display example is, the cash symbol $, the yen symbol, the euro symbol, emojis and more) 

By creating this little economy scenario, huge potential fun doors open for Miki Bot. 

A duel system can be added that would allow members to duel one another. The member who loses pays the winner a small ammount of $. 
With a duel system added, an item shop can be made that gives minor stat upgrades to members to improve their chances of winning duels. It would also provide another reason to make $ and a way to spend $. 
Fun minigames that give extra $ can be added. 
Bot admins could charge members with fines on their income for minor rule violations and stuff like that. 

**Regarding a guild system...**
The guild system is still a bit confusing to me, but I manage a general community gaming server. I have a few guilds, clans, and groups. 
Giving certain members the ability to form guilds with a particular role would be amazing. They can manage their guild members, have their own list of members, remove guild, clan, or group members and add people. 

These are just some ideas Miki Bot could add that would make it an incredible and enjoyable bot. With these additions, it would be possible to remove other bots and just use Miki! Hopefully these ideas are something that can be added! Thank you for reading!

**Comment by adv0catus** [comment]
Roles.
1. In the Planned category of the Trello development roadmap.
2. This is a feature already.
3. This is a feature already.

Welcome/Goodbye Messages.

1. This is a feature already. Miki says the messages in the channel you use the command in.

NSFW.
1. If you have a suggestion for a new site with adequate API support, please suggest it here: https://feathub.com/Mikibot/Miki/
2. Already a feature, just toggle "NSFW" in channel settings.

Economy.
1. Not applicable.
2. Not going to happen, will destroy balance. Mekos are global.
3. Not going to happen, will destroy balance. Mekos are global.
4. You don't earn money for chatting any more.
5. This is already a feature, use `>help give` for more information.
6. This is already a feature, use `>help mekos` for more information.
7. Mekos are global, this can't happen.
8. This has already been discussed and has been determined that this will never happen.
9. Suggest this on FeatHub.

A dual system has already been suggested.
Many gambling/"minigames" have already been suggested, feel free to suggest specific ones that have been missed.
Fines can be managed by the server owner.

Guild System.

When Miki says "Guild", she means the actual server that she's in. It's Discord's word for server (they're interchangeable).

**Comment by velddev** [comment]
Please use https://suggestions.miki.ai/ for ideas.
