### ISSUE TITLE
achievement does not work

### ISSUE THREAD

**Issue by meankarma** [veldlabs/miki-bot#398]
the ship girl achievement does not work.

I noticed the ship girl achievement wasn't disabled but whenever I said the secret phrase it would not give the achievement. I looked at the code and i think it might be missing parentheses after
`x.Achievements = new List<BaseAchievement>`
in
Miki/Miki/Modules/Accounts/Services/AchievementsService.cs

**Comment by goderek91** [comment]
what the secret phrase? let me test it :)

**Comment by adv0catus** [comment]
@goderek91 you can simply read the source code to see the secret phrase. But it indeed does not work so it doesn't matter anyways.

**Comment by coehlrich** [comment]
The Lenny achievement doesn't seem to work either.
