### ISSUE TITLE
>lottery displaying error on some servers.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#399]
**What went wrong?**

~~The >lottery command is non-responsive when Miki is not able to display the name of the previous winner.~~

`>lottery` stops working.

**How do I reproduce this issue?**

~~Use >lottery when the previous winner has no name. This is an intermittent issue.~~

Not sure of cause.

**Comment by xialight** [comment]
Should be fixed this patch

**Comment by adv0catus** [comment]
![](https://i.imgur.com/3ChxUpI.png)
