### ISSUE TITLE
Chef is awarded even when a new pasta isn’t created.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#401]
**What went wrong?**

When >createpasta <name> is used, Chef is awarded even if a new pasta isn’t made (the name is in use).

**How do I reproduce this issue?**

Using an account without the achievement, create a new pasta with a pre-existing name.

**Comment by adv0catus** [comment]
![](https://i.imgur.com/gAoS7gp.jpg)

**Comment by velddev** [comment]
Should be fixed once error handling gets reworked.

**Comment by Zenulous** [comment]
This is fixed.
