### ISSUE TITLE
cannot open GIF

### ISSUE THREAD

**Issue by willy7im** [veldlabs/miki-bot#407]
![fb672bdb-ff7d-4871-bd8d-9eb5d43a564e](https://user-images.githubusercontent.com/38461268/38886020-e266706c-429e-11e8-9c91-71d50556bdfb.jpeg)
**What went wrong?**
i cannot open all the GIF image. it only show “failed to load image. please try again”. i already try many times. i still show the same thing

**How do I reproduce this issue?**

**Comment by Sworduster** [comment]
it is not a miki issue.
 you are in a school wifi or something maybe ?

**Comment by xialight** [comment]
Seems like maybe a mobile issue also.
