### ISSUE TITLE
Blackjack is rigged.

### ISSUE THREAD

**Issue by taynguyen22** [veldlabs/miki-bot#409]
I don't know where the blackjack system came from, but the first couple games I have played have been somewhat fair, where my friends and I were able to win. After a day, a couple of us on Discord played blackjack again, but this time, no matter how small or big the bets were, we just lose. I think it was a 40% win rate the first day, but after that, it dropped to about less than 10%. 

I don't know of any fixes to this, or if anyone else is experiencing this with their bots, but it's both funny, yet discouraging to use this feature, a game which I love to spend my down time on.

**Comment by adv0catus** [comment]
Here's the source code, feel free to read it: https://github.com/Mikibot/Miki/blob/master/Miki/Modules/Gambling/GamesModule.cs#L182

**Comment by velddev** [comment]
Sadly. This all purely comes down to luck. As notated above. The source code is open and there's nothing related to rigging and/or ways to make Miki cheat.

I've added some extra stuff for blackjack, but I don't know how to fix luck. :(
