### ISSUE TITLE
Marriage slots are stuck at 3

### ISSUE THREAD

**Issue by IA-Xerise** [veldlabs/miki-bot#41]
Also it should be user does not ... not user do not
![image](https://cloud.githubusercontent.com/assets/24828421/21669988/8e9f64d8-d2de-11e6-8099-09d54e3ab29a.png)

**Comment by velddev** [comment]
Confirmed bug.

Another extra note. For unspecified reason I got to see my proposals in my list too.

**Comment by velddev** [comment]
This is resolved on 0.1.100
