### ISSUE TITLE
Favorite Command count is bugged

### ISSUE THREAD

**Issue by xialight** [veldlabs/miki-bot#410]
**What went wrong?**
Favorite Command count on `>profile` is borked

**How do I reproduce this issue?**
Type `>profile`, look at your favorite command, do your favorite command, type `>profile` and you notice that it didnt go up.

**Comment by adv0catus** [comment]
Could be that it's not updated in real-time.

**Comment by SnipeFrost** [comment]
its borken for 2 weeks already , also i think all commands just no counting, cuz lb commands not updated too

**Comment by xialight** [comment]
I know, just putting it on github

**Comment by velddev** [comment]
I'm aware of this. It was taking up a lot of database time for the little time. It will stay this way until further optimizations are finished.

**Comment by adv0catus** [comment]
This feature no longer exists.

**Comment by SnipeFrost** [comment]
thanks for commenting its after 2 years
