### ISSUE TITLE
Please tell me this is another bug?

### ISSUE THREAD

**Issue by ghost** [veldlabs/miki-bot#412]
**What went wrong?**
![image](https://user-images.githubusercontent.com/38775102/39403246-290fb876-4ba9-11e8-8a23-111b45b781a2.png)
all of his mekos are gone after doing that and he didnt level up

**How do I reproduce this issue?**

**Comment by adv0catus** [comment]
This is a two part issue:

1. Miki doesn't have a check to ensure that the CDN is responding correctly.
2. The CDN had a network-side issue that is (probably) out of control of Miki/Veld.

**Comment by ghost** [comment]
May I know what is CDN?

**Comment by adv0catus** [comment]
CDN stands for Content Delivery Network. It's basically a bunch of data centers all over the world that move your data around for you. Digital Ocean is the CDN company that Miki uses and when you were trying to buy that role, the network was having some sort of problem and prevented your command from going through.

**Comment by ghost** [comment]
so its another bug that youre gonna fix right?

**Comment by velddev** [comment]
@caryllelol I think you must've forgotten to allow miki to manage roles. make sure she can actually pass roles to your users

**Comment by velddev** [comment]
The CDN has nothing to do with roles, so I'm not sure how they are linked,
