### ISSUE TITLE
Can't check profile info for offline (uncached?) user.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#413]
**What went wrong?**

![](https://i.imgur.com/FGRhNHZ.png)

Trying to check the balance of an alternate account and this was happening. Only fixed itself when the account went online. Once it was online, it being offline again didn't matter any more.

**How do I reproduce this issue?**

**Comment by Sworduster** [comment]
Discord not cashing offline issue right ? before it just didnt show any error message
