### ISSUE TITLE
>createpasta doesn't work.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#414]
**What went wrong?**

![](https://i.imgur.com/r18T1Y2.png)
![](https://i.imgur.com/CHSJFo1.png)

Nothing happened; Miki didn't respond and the pasta wasn't created.

**How do I reproduce this issue?**

Try to create a new pasta.

**Comment by velddev** [comment]
Resolved in https://github.com/Mikibot/Miki/commit/2d67554c3f90db5e93bfdfd77226c21418d73b1d, but I'm keeping it open until all feedback routes are implemented

todo:
- [x] error message for duplicate pasta.
- [x] error message for no text
- [ ] confirmation message for success.

**Comment by adv0catus** [comment]
Even with Miki still not stable, this appears to be working again, so I'll close this. If it becomes an issue again, I'll reopen.
