### ISSUE TITLE
Update event failed to save. Precondition 412 failed to save.

### ISSUE THREAD

**Issue by ghost** [veldlabs/miki-bot#415]
The exchange did not save and I had to abort the sync. Have updated from previous version to latest, still getting this error message.

[Precondition 412.docx](https://github.com/Mikibot/Miki/files/1958949/Precondition.412.docx)

**Comment by adv0catus** [comment]
Are you trying to self-host? No support is provided for that.

**Comment by ghost** [comment]
Hi,

 

I wish I knew what you were talking about.

I find a lot of the website, quite technically high for the normal person.

 

I am a private individual, who uses Outlook 2010 to fill in his diary and because I have an iPhone and a Samsung, therefore two OS’s, I use your product, which I have also made donations to. But all of a sudden it won’t work!! It wasn’t broke before!

 

Can you assist??

Regards

 

Lachie Tod

**Comment by adv0catus** [comment]
This has nothing to do with Miki. Please use Google to find an appropriate technical support forum.

**Comment by velddev** [comment]
Miki has no gmail sync functions, but you might want to check new gmail apps.

**Comment by ghost** [comment]
So why is it  happening?? I haven’t had a resolve.

 

 

Regards

 

Lachie Tod

**Comment by adv0catus** [comment]
We can't help you. This is the wrong place.
