### ISSUE TITLE
Blackjack Broken?

### ISSUE THREAD

**Issue by Grifter45** [veldlabs/miki-bot#416]
**What went wrong?**
Recently the >blackjack command has been "cheating". It used to be where if Miki and I both got the same number on our cards I would get my bet back, but now if we both get the same number Miki keeps the bet. 

**How do I reproduce this issue?**
Use the >blackjack [number] command until you and Miki both have matching card totals, and she will keep the bet.

**Comment by adv0catus** [comment]
That's the new Blackjack rules.

https://blog.miki.ai/miki-0-6-1-update-log/

**Comment by Grifter45** [comment]
Well that's kinda dumb, but thanks for answering so quickly adv0catus!

**Comment by adv0catus** [comment]
It’s to adhere to Blackjack’s rule book.
