### ISSUE TITLE
Miki is not following the rules for BlackJack. Losing bet on tied hands. Wasn't happening before 4/29.

### ISSUE THREAD

**Issue by IndecisiveBoolean** [veldlabs/miki-bot#417]
**What went wrong?**
I used the >blackjack command and the hand ended in a tie which should return the bets to the players in blackjack. However I lost my bet. The hand is as follows.

![blackjack-4-29](https://user-images.githubusercontent.com/29291906/39414167-90d85d9c-4c02-11e8-8198-3afadd0954ea.JPG)

Another user in the same Discord as me also noticed this as they had bet 1,000 and lost due to a tie. This was not occurring as of 4/28 and before it has started today 4/29.

Here is a match that I played on 4/28.
![blackjack-4-28](https://user-images.githubusercontent.com/29291906/39414184-ba9989d0-4c02-11e8-84f4-33be3abfb86a.JPG)

**How do I reproduce this issue?**
Play a hand of Blackjack with Miki that ends in a tie.

**Comment by trick4ndTreat** [comment]
It's part of the new update. As all the blackjack rules, draw is favoured by the host.
"blackjack: Draws are now in favor of Miki, as blackjack rules notate."

**Comment by IndecisiveBoolean** [comment]
Those are not the rules of Blackjack though. If the dealer and player both tie including with a blackjack the bet is considered a tie or a push and the bet is neither lost or paid.
