### ISSUE TITLE
Can't set front color (beta)

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#418]
**What went wrong?**

*I know this is a beta feature.*

![](https://i.imgur.com/XbxjogV.png)
![](https://i.imgur.com/bFFYvYk.png)

First time trying to change my colour and it giving me an error message and not changing the colour. Someone else on the Miki support server has a different colour, so something has caused it to not work any more/selectively work. Note: Insufficient mekos isn't the issue and it isn't taking the mekos.

**How do I reproduce this issue?**

Try to change the front color.

**Comment by williamjcm** [comment]
It doesn't work on a server I'm in, but Miki doesn't report an error.

In fact, she says that the colour was changed successfully, but nothing changes.

**Comment by adv0catus** [comment]
It changes now, but just to grey.

**Comment by adv0catus** [comment]
This appears to be resolved now.
