### ISSUE TITLE
Blackjack was a push, but I lost my Mekos

### ISSUE THREAD

**Issue by taynguyen22** [veldlabs/miki-bot#419]
**What went wrong?**
So I was playing a game of Blackjack with Miki, and it resulted in a push; I had an 18 and so did she. Apparently, I lost, and this my Mekos was taken away from me.  Is this a new rule of the game, where pushes don't apply, or was it a bug. If its the latter, am I able to get my Mekos back?

**Comment by adv0catus** [comment]
It’s the new blackjack rules.
