### ISSUE TITLE
>divorce displays names by who proposed first.

### ISSUE THREAD

**Issue by IA-Xerise** [veldlabs/miki-bot#42]
![image](https://cloud.githubusercontent.com/assets/24828421/21668651/da3b54c2-d2d1-11e6-95ab-2a7b19578f9c.png)
but when i proposed to n0t first then divorced this happens
![image](https://cloud.githubusercontent.com/assets/24828421/21668815/81b1f57a-d2d3-11e6-804b-4aab86b3e448.png)

**Comment by velddev** [comment]
Fixed in 0.1.9.9
