### ISSUE TITLE
Miki always disables achievement event not service.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#420]
**What went wrong?**

![](https://i.imgur.com/33FjImz.png)

Miki is confused with the event and the service both being called (a/A)chievements. When you use `>setevent` to try and disable the service, it always disables the event instead. Miki ignores capitalization.

**How do I reproduce this issue?**

Attempt to disable the Achievements service.

**Comment by velddev** [comment]
Merging this issue with #421
