### ISSUE TITLE
Createpasta command not functioning. 

### ISSUE THREAD

**Issue by Warlordzair** [veldlabs/miki-bot#428]
I'm trying to create a pasta, but when I do >createpasta <name> <content> it doesn't create a pasta. I did not actually include the < and >, as I've made Pastas before and aware you don't include those. 

Reproduce by simply trying to create a pasta. It won't make the pasta, merely act as though it's a simple text message in the chat.

**Comment by adv0catus** [comment]
This has already been reported here: https://github.com/Mikibot/Miki/issues/414 but thank-you for the help. :)
