### ISSUE TITLE
[Suggestion, not issue]: Able to repeat a reminder

### ISSUE THREAD

**Issue by celcharm** [veldlabs/miki-bot#429]
This is not so much an issue but a suggestion: 
It would be useful to add another option so that we can set a reminder to repeat (e.g. every 30 mins) so we don't have to keep setting multiple reminders with a 30 mins span for each reminder. 

Thanks for your time!

**Comment by adv0catus** [comment]
In future, you can make suggestions here: https://feathub.com/Mikibot/Miki/

You can do this already: `>remind {task} *every* {time}`.

**Comment by celcharm** [comment]
Thanks for letting me know! I'm new to this :)
