### ISSUE TITLE
Cannot channel override >server disable with >channel enable

### ISSUE THREAD

**Issue by IA-Xerise** [veldlabs/miki-bot#43]
![image](https://cloud.githubusercontent.com/assets/24828421/21668765/ef2e408c-d2d2-11e6-9ce1-6c6742f697ad.png)

**Comment by velddev** [comment]
confirmed bug, will look into it

**Comment by IA-Xerise** [comment]
Found a work around for now using modules. I will look into how this effects other commands like `>ping` and the like.
![image](https://cloud.githubusercontent.com/assets/24828421/22865726/06a2ac66-f138-11e6-921f-7eb2efbdfa66.png)
![image](https://cloud.githubusercontent.com/assets/24828421/22865729/1736bea0-f138-11e6-9462-72cfc9216a20.png)

**Comment by IA-Xerise** [comment]
Fixed in 0.2.1
![image](https://cloud.githubusercontent.com/assets/24828421/25366199/17a9aa50-293c-11e7-9bf0-9baf14cf36ba.png)
