### ISSUE TITLE
Level Permissions

### ISSUE THREAD

**Issue by LoliLewding** [veldlabs/miki-bot#431]
**What went wrong?**
There's no way to disable the leveling system, but I already have two, I can't turn off this one, while the others allow me too. Please add a way to disable the leveling system (server based).

**How do I reproduce this issue?**
Self explanatory.

**Comment by adv0catus** [comment]
Hey, thanks for the ticket. Are you referring to not being able to turn off the Experience service in the Accounts module? Currently have a ticket open for that.

**Comment by velddev** [comment]
duplicate to #421 move conversation about this topic there
