### ISSUE TITLE
>lovepasta/>hatepasta work with no argument.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#433]
**What went wrong?**

![](https://i.imgur.com/OfKLh3C.png)

If you use `>lovepasta` or `>hatepasta` but don't specify a pasta, the +1/-1 is added to a blank/empty pasta's score.

**How do I reproduce this issue?**

Use `>lovepasta` and `>hatepasta` with no argument.

**Comment by velddev** [comment]
Resolved in https://github.com/Mikibot/Miki/commit/2d67554c3f90db5e93bfdfd77226c21418d73b1d
