### ISSUE TITLE
>whois doesn't display roles without a hex colour.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#436]
**What went wrong?**

![](https://i.imgur.com/sJyKDFl.png)

If a user has a role that has no colour hex assigned to it, whois doesn't display it.

**How do I reproduce this issue?**

Have both a role with a colour hex and one without it and use `>whois`.

**Comment by velddev** [comment]
https://github.com/Mikibot/Miki/commit/06a32627cebd9951e6f9983d9f0c2718f75d432b#diff-8d471436d263fb563b4feebe412d2541R522 fixed it.
