### ISSUE TITLE
>whois returns non-user-friendly errors when passed erroneous parameters

### ISSUE THREAD

**Issue by Pao-Lumu** [veldlabs/miki-bot#437]
# **What went wrong?**
Erroneous parameters cause unhelpful errors to appear for the end user.

# **How do I reproduce this issue?**
The following will return "Object reference not set to an instance of an object":
`>whois`
`>whois <@SOMEONE_WITH_NO_COLOR_ROLES>`

The following will return "Value cannot be null. Parameter name: user":
`>whois <any non-mentioning string>` i.e. `>whois it?`
`>whois <#CHANNEL_NAME>` i.e. `>whois #general`
`>whois <@ROLE_NAME>` i.e. @Admins, @everyone

**Comment by moojpy** [comment]
On certain servers if you do `>whois` by itself, it might return the info on a random user... implying that the user has a colored rank and **he has no nickname.**

This seems to vary according to the presence, or maybe even the lack thereof, of nicknames on the server.

**Tatsumaki has no nickname, but Miki has the nickname "Eighty."**
![image](https://user-images.githubusercontent.com/17146628/39783913-aa74ac5e-52e4-11e8-9554-924b1762e9be.png)

**Tatsumaki was given the nickname "Tatsu." Everybody else on the server is also nicknamed.**
![image](https://user-images.githubusercontent.com/17146628/39783951-c2f01c50-52e4-11e8-82f4-be31a7df869f.png)

**I reset Miki's nickname.**
![image](https://user-images.githubusercontent.com/17146628/39783962-d26a81de-52e4-11e8-9a3f-104dace9be23.png)

**I removed my own nickname after re-nicknaming Miki and Tatsu.**
![image](https://user-images.githubusercontent.com/17146628/39784064-2573f072-52e5-11e8-97eb-eb35a051dd59.png)

**I'm the only non-nicknamed person and I removed all my ranks.**
![image](https://user-images.githubusercontent.com/17146628/39784181-8a45d0e2-52e5-11e8-8b3c-bc3bc7e20302.png)

**Still same, but this time I gave myself a non-coloured rank.**
![image](https://user-images.githubusercontent.com/17146628/39784305-f73733d0-52e5-11e8-9ced-c2731c96e2cc.png)

**This time, alongside the non-coloured one, I gave myself a coloured rank.**
_Notice how only the coloured rank (Drag Queen) shows up in the roles list as well._
![image](https://user-images.githubusercontent.com/17146628/39784267-cfccc6b6-52e5-11e8-8b86-76b13217010e.png)

**With the colorless new role I created but with added color, it suddenly works:**
![image](https://user-images.githubusercontent.com/17146628/39784377-2b964486-52e6-11e8-9baa-b82d719f8098.png)

**And there it is returning Peggy (my test alt) that has a higher role than me currently:**
![image](https://user-images.githubusercontent.com/17146628/39784465-81c66390-52e6-11e8-8e76-354a54ea8566.png)

Another thing to denote is that there are other users with colored ranks on my server, it also seems to grab non-nicknamed user with the highest colored role in the hierarchy.

This seems iffy either way. I can reproduce this on two servers, but, for example, on the miki support server it always gives back `Object reference not set to an instance of an object.` even though there are definitely people with coloured roles who are also going without nicknames (namely me). 

Hopefully this helps.

**Comment by adv0catus** [comment]
![](https://i.imgur.com/lUyjtTq.png)
