### ISSUE TITLE
Unable to switch to Chinese using setlocale

### ISSUE THREAD

**Issue by TheresaQWQ** [veldlabs/miki-bot#443]
![qq 20180517212850](https://user-images.githubusercontent.com/22370654/40180408-52bd76c6-5a19-11e8-9acd-98b57fa68c6c.jpg)

**Comment by velddev** [comment]
This function has been fixed with https://github.com/Mikibot/Miki/commit/558c798b7540ea0393ac0b94106dfd59bdc3de23
