### ISSUE TITLE
Voted for Miki on DiscordBots and didn't receive mekos.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#444]
**Describe the bug**

While logged into DiscordBots, I voted for Miki. Received the confirmation from DiscordBots that the vote was received as successful (not within 24 hours of my last vote) and I did not receive the 200 mekos from Miki. At the bare minimum, there was no DM sent.

**To Reproduce**
1. Log into DiscordBots.
2. Vote for Miki more than 24 hours after last vote.
3. Hopefully reproduce the issue.

**Expected behavior**

Receiving a DM with the confirmation of 200 mekos.

**Screenshots**

Confirmation of vote: ![](https://i.imgur.com/beFm5w0.png)
Confirmation of no DM: ![](https://i.imgur.com/99El49L.png)

**Additional context**

This issue might not be reliably duplicateable as it hasn't really come up as a recurring issue in #support.

**Comment by velddev** [comment]
This was an issue related to the webhook connection service being down. It has been resolved now.
