### ISSUE TITLE
>daily reset at midnight GMT.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#449]
**Is your feature request related to a problem? Please describe.**

Not a problem per say, but definitely an inconvenience.

**Describe the solution you'd like**

A consistent, set time for `>daily` to reset, same as `>rep`.

**Describe alternatives you've considered**

Alternatives don't make much sense since doing this would bring `>daily` in line with `>rep`.

**Additional context**

Earliest reference in #suggestions with this idea that I could find: ![](https://i.imgur.com/bwd8LLZ.png)

**Comment by velddev** [comment]
Ideas are no longer supposed to be here, please add this idea to https://suggestions.miki.ai
