### ISSUE TITLE
>rep breaks at 0 seconds count down.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#450]
**Describe the bug**

If you use `>rep` when the reset counter hits 0 seconds, the command breaks and Miki displays an error.

**To Reproduce**

Do `>rep` at exactly midnight GMT.

**Expected behavior**

It would say 0 seconds or 24 hours.

**Screenshots**

![](https://i.imgur.com/0gPOQA6.png)

**Additional context**

If I recall, other commands do this too, but I don't remember specifics off hand. (`>weekly`?)

**Comment by velddev** [comment]
Fixed in https://github.com/Mikibot/Miki/commit/a45bba381399ce7f23543c0453fa80c06ce98c7d
