### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by LovingMelody** [veldlabs/miki-bot#452]
**Is your feature request related to a problem? Please describe.**
It's truly heart breaking when I wake up and I don't see the latest and greatest of whats happening on Miki when I check my "Whats happening" feed

**Describe the solution you'd like**
RSS feed for [Miki's blog](https://blog.miki.ai).

**Describe alternatives you've considered**
Email Newsletter

**Comment by vallode** [comment]
I guess there is no link to it but the blog _does_ indeed have an rss feed.
https://blog.miki.ai/rss/ :smile:

**Comment by velddev** [comment]
you can also follow the twitter, it automatically posts new entries https://twitter.com/miki_discord and you can subscribe to our email newsletter https://blog.miki.ai/#subscribe 👍

**Comment by LovingMelody** [comment]
Please add links to these helpful resources at the footer.

**Comment by velddev** [comment]
On the blog? It's managed by ghost for the time being.

**Comment by adv0catus** [comment]
I think Fuzen means a link to the RSS (if not shown already) and a link to subscribe.

**Comment by velddev** [comment]
As I said, the footer on the blog are managed by ghost, and I haven't looked into custom skinning yet; Therefore, I can't edit it

**Comment by adv0catus** [comment]
Oh, gotcha.
