### ISSUE TITLE
Not receiving bonus daily after voting for Miki. 

### ISSUE THREAD

**Issue by Jessie2488** [veldlabs/miki-bot#453]
**Describe the bug**
 Voted for Miki on DiscordBots and did not receive mekos or PM from Miki, but was logged in and got confirmation that vote was received.

**To Reproduce**
1. Log into DiscordBots.
2. Vote for Miki 24+ hours after last vote.

**Expected behavior**
Receive PM from Miki and bonus mekos.

**Screenshots**
![untitled](https://user-images.githubusercontent.com/39543746/40401659-6d12deee-5e15-11e8-9702-45703f9bc242.png)

**Additional context**
Worked fine on 5/14/18 but has ceased to work since.

**Comment by BlackKite84** [comment]
same too

**Comment by velddev** [comment]
Hey guys, Currently the voting system is down, but will be back next update. Something went horribly wrong, and I can't fix it at the moment. I'll put it on high priority

**Comment by adv0catus** [comment]
I say with a high degree of certainty that this will not be returning as a feature/mechanic for Miki, so I'm going to close this. https://github.com/Mikibot/Miki.Bot/pull/501

**Comment by velddev** [comment]
This should've been fixed now
