### ISSUE TITLE
Minor profile information flair.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#454]
**Additional context**

- [ ] `>setflag <emoticon>` to display the user's country.
- [ ] `>setgender <male/female/other(?)>` to display the user's gender.
- [ ] `>setbday` <dd/mm/yyyy>` to enter the user's birthday so Miki can wish them a happy birthday on that day.

**Comment by adv0catus** [comment]
![sample_profile_flair](https://user-images.githubusercontent.com/10149775/40585855-5519c652-6187-11e8-87ab-e8583676d890.png)

**Comment by velddev** [comment]
Ideas are no longer supposed to be here, please add this idea to https://suggestions.miki.ai
