### ISSUE TITLE
Cannot be set to Simplified Chinese.

### ISSUE THREAD

**Issue by popooto** [veldlabs/miki-bot#456]
**Describe the bug**
Miki is a very cool robot. But I encountered some problems during the setup and could not be set to Simplified Chinese. I first used >listlocale to query the list of supported languages and then used the >setlocale chinese simplified command when prompted, but was prompted "Something went wrong!
Chinese is not a valid language. use >listlocale to check all languages available.". I tried "setlocale japanese". The language was successfully set to japanese.

**Expected behavior**
I checked the wiki that there was nothing wrong with the command I entered. I'm not sure how this happened.

**Screenshots**
![1245689-0](https://user-images.githubusercontent.com/16750927/40490182-925f4276-5f9d-11e8-9ae0-4cbce802d7a7.png)

**Additional context**
After that I tried the "setlocale chinese simplified" "setlocale chinese_simplified" "setlocale chinese-simplified" and other commands. Obviously it failed.:sweat:

**Comment by adv0catus** [comment]
Veld has fixed this and it will be live next update.

https://github.com/Mikibot/Miki/issues/443

**Comment by velddev** [comment]
I'll keep it open until the update goes live, I suppose

**Comment by popooto** [comment]
@adv0catus @velddev 
Sorry I didn't notice that this issue has been submitted. Thank you again for your help.

**Comment by TokoAd** [comment]
My friend! Time has passed for some time. I don't know how your recent progress has been. Has this small problem been repaired? Or what progress has been made?

**Comment by adv0catus** [comment]
This fix appears to be live and working, so I'll close this.
