### ISSUE TITLE
>iam command not working

### ISSUE THREAD

**Issue by Jessie2488** [veldlabs/miki-bot#459]
**Describe the bug**
Using >iam command to self assign roles not working properly
**To Reproduce**
1. Use >iam command on role you want

**Expected behavior**
Role then be assigned

**Screenshots**
![screenshot_20180530-160821](https://user-images.githubusercontent.com/39543746/40744875-e4b53b90-6423-11e8-8dea-f914aa482bae.png)

**Additional context**

**Comment by velddev** [comment]
Give Miki the ability to manage roles.

**Comment by Jessie2488** [comment]
One of the mods in the server says that Miki does have the ability to manage roles.

**Comment by adv0catus** [comment]
With Manage Roles permission:

![](https://i.imgur.com/bmnDQLu.jpg)

Without Manage Roles permission:

![](https://i.imgur.com/CDhS9xP.jpg)

Tested less than 5 minutes ago. The role Miki that was auto generated when Miki was invited is what needs to have Manage Roles permission.

**Comment by Jessie2488** [comment]
I'll have them check again

**Comment by adv0catus** [comment]
If they still say Miki has the permission and it's not working, join the Miki support server and request assistance in #support which will likely involve a support staff requesting an invite to the server and admin permissions (temporarily).

As far as I can tell, the command is working as intended.

**Comment by Jessie2488** [comment]
Ok I'll pass this forward

**Comment by Jessie2488** [comment]
It seems to be only leveled roles not working

**Comment by velddev** [comment]
Make sure that the role is not above miki's role either. Miki can not give roles that she does not have access to

**Comment by Jessie2488** [comment]
Thanks

**Comment by velddev** [comment]
To resolve this issue:
- [x] add userfriendly check for manage roles permission
- [x] add userfriendly check for roles above miki

**Comment by Jessie2488** [comment]
We fixed it. Thanks for the help.

**Comment by velddev** [comment]
This has been resolved since [0.7b](https://blog.miki.ai/update-v0-7b/)
