### ISSUE TITLE
level achievements 

### ISSUE THREAD

**Issue by chlobuggy** [veldlabs/miki-bot#461]
okay so im on level 36 and Miki has yet to give me my achievements and im wondering whats going on
please help! thanks.

**Comment by velddev** [comment]
Hi, yeah there might be some issues with achievements. Not sure what it is yet.

**Comment by Ang3lbee** [comment]
<img width="606" alt="Screen Shot 2019-04-08 at 11 27 44 am" src="https://user-images.githubusercontent.com/49397899/55720233-7e4e2200-5a3f-11e9-9b05-4bc4cb270ed1.png">

So I've reached Level 100 on a local server and I didn't receive the Level 100 achievement. Also on a side note, I don't think I got the Minted achievement either. Not sure whether you have to get 125k on a local server though.
