### ISSUE TITLE
>guildnewrival 

### ISSUE THREAD

**Issue by miyulp** [veldlabs/miki-bot#462]
Every time i try to set my rival, the same thing pops up. “We couldn’t matchmake you right now. Try again later!” I was just wonder what this means. Is there no way for me to get my rival? It’s been like this for a while now, and I know it’s not just me since I saw other servers with the same problem.

**Comment by adv0catus** [comment]
How many people are in your server?

**Comment by velddev** [comment]
reinvite miki
