### ISSUE TITLE
Upvoting issue

### ISSUE THREAD

**Issue by LycanAlpha** [veldlabs/miki-bot#468]
**Describe the bug**
Upvoting gives no rewards
**To Reproduce**
1. Go to https://discordbots.org/bot/160105994217586689/vote
2. Click on Vote
3. message says thank you for the vote
4.Open discord
5. check bots dm:s and your currency

**Expected behavior**
Miki dms you and adds money to your account 

**Screenshots**
http://prntscr.com/jslfzr

**Additional context**
This issue has been noted with few other bots on same website

**Comment by adv0catus** [comment]
https://github.com/Mikibot/Miki/issues/453

This is a known issue.
