### ISSUE TITLE
Daily Streak

### ISSUE THREAD

**Issue by Krysora** [veldlabs/miki-bot#472]
**Describe the bug**
daily streak reset after 33 days
**To Reproduce**
just get a 33 daily streak and on the 34th day the streak will be lost
**Expected behavior**
expected to receive 780 mekos
**Screenshots**

**Additional context**

**Comment by velddev** [comment]
Our cache basically stopped responding, and made us lose the settings. I'll need to find a better system for them.

**Comment by Umbrawolve** [comment]
This is the second time this has happened since the streak was implemented right?

**Comment by velddev** [comment]
Sadly it has, I made precautions for it to not happen again; however, it happened again.
