### ISSUE TITLE
No daily at all

### ISSUE THREAD

**Issue by Kelly164** [veldlabs/miki-bot#473]
For 2 days of you type the daily command nothing happens.. But It did in a different text channel

**Comment by velddev** [comment]
Miki was down for last night, should respond again now; otherwise check your permissions

**Comment by Kelly164** [comment]
It was just now (in the last hour) and 24 hour before that

**Comment by velddev** [comment]
![image](https://user-images.githubusercontent.com/13852840/41579890-0bc4a3a4-7399-11e8-8bd0-ea47374e7faa.png)
It works quite well for me, consider checking your settings

**Comment by Kelly164** [comment]
Yeah it works again... But I did lost my streak unfortunately

**Comment by velddev** [comment]
yep. everyone did; sadly.

**Comment by adv0catus** [comment]
Daily has seemingly been working for a while now, with the command itself working and maintaining the streak.
