### ISSUE TITLE
Syncavatar gets rid of profile picture in exp

### ISSUE THREAD

**Issue by Dayveen** [veldlabs/miki-bot#480]
![15fc9620-ab3f-4502-9b21-fc30e4953562](https://user-images.githubusercontent.com/41290910/42756049-e293a082-88d0-11e8-83ef-4e9636273d75.jpeg)
![9fcd70e4-1cc8-417d-baa0-e71f29a941ed](https://user-images.githubusercontent.com/41290910/42756050-e2b61c16-88d0-11e8-894b-6957ddc41c55.jpeg)

**Describe the bug**
When you do the command >syncavatar then go to check your exp your profile picture is not there and is just blank

**To Reproduce**
1. Type >syncavatar 
2. Type >exp

**Expected behavior**
My new profile picture being there instead of nothing 

**Additional context**
It happened everytime someone tried doing it on my server

**Comment by adv0catus** [comment]
As well as `>ship`.

**Comment by adv0catus** [comment]
Do >syncavatar again to fix this.
