### ISSUE TITLE
>profile not working

### ISSUE THREAD

**Issue by ShadowReaperS** [veldlabs/miki-bot#483]
Can't use every command in my disc server and >profile is one of them

**Comment by Xetera** [comment]
There are still issues with commands along with some other things but they're being worked on. According to veld the only thing that's really working right now is the uptime. I'd recommend asking this in the support server instead of opening a new issue btw.

**Comment by adv0catus** [comment]
`>profile` works, but for some reason `>Profile` doesn't.

**Comment by adv0catus** [comment]
Seems like this is resolved, possibly this was caused by the caps bug.
