### ISSUE TITLE
Divorce not working

### ISSUE THREAD

**Issue by SadTomatoo** [veldlabs/miki-bot#488]
I have been trying for months to delete my ex off my marriages. I see other people have this bug as well. When will this be fixed?

**Comment by adv0catus** [comment]
We have a ticket for this already https://github.com/Mikibot/Miki/issues/481
But thanks for your contribution. :)

Miki is going through a lot of back-end changes right now and commands are being fixed as soon as possible. Divorce is definitely on the list and will be fixed ASAP.
