### ISSUE TITLE
After typing ">prefix" and then "``help" NOTHING happens.

### ISSUE THREAD

**Issue by Xzoesc** [veldlabs/miki-bot#49]
For some reason,it just fails to work :/
I have no idea if this is a bug or something. I think it's a bug though.

Sidenote: Nothing works after I wrote that one specific command.

**Comment by oxocero** [comment]
![ugh](https://cloud.githubusercontent.com/assets/25203616/22070377/1474c4d2-dd9c-11e6-9a0a-c438d5d81851.png)
indeed

**Comment by rosieneko** [comment]
When you type `>prefix` without the prefix after that you want (e.g., `>prefix .` to set the prefix to .), it will remove all prefix. You would access the commands without an actual prefix.

To reset it back to the default, use `miki.prefix >` to set it back to the default prefix.

As for the screencap, does Miki respond to mentions? (e.g., @Miki hi there). If not, then it means Miki has temporarily crashed and will be back up.

**Comment by oxocero** [comment]
I've tried it 15 times over the span of 1.5hours. ugh

**Comment by Xzoesc** [comment]
Thanks. I just don't really know how to use bots that much and I'm pretty new to server creating.

**Comment by velddev** [comment]
Keep this open though. It seems to be a accounts issue.
