### ISSUE TITLE
can't invite Miki back to the Discord

### ISSUE THREAD

**Issue by beaniemoo** [veldlabs/miki-bot#490]
**Describe the bug**
I think Miki was bugging so we kicked her out of our Discord. And now when we invite her back, there's not an option to choose the Discord channel. Every channel I'm in is grey out although I'm a mod in all of the channels. 
Anyone having the same problem?

**Comment by adv0catus** [comment]
The options in the invite link are grey but you should still be able to click the server you want. If you can't or don't see any options, you don't have the proper permissions needed to invite bots.

Edit: You need the `Manage Servers` permission.

**Comment by beaniemoo** [comment]
I'm the owner of the server. How come I don't have enough permissions? There is no server option to choose. 
We were bugging in the middle of it when we kicked Miki. So we think she's bugging and can't get back in.

**Comment by velddev** [comment]
Could you send me an invitation to the server through discord DM? (Veld#0001). Sorry for the long time waiting, I have been very busy fixing all kind of miki-related issues.
