### ISSUE TITLE
Bot can ping @everyone with >pasta command

### ISSUE THREAD

**Issue by dct0** [veldlabs/miki-bot#492]
**Describe the bug**
Miki can ping `@everyone` with >pasta command.
It ignores permissions.

**To Reproduce**
1. Make a new pasta with the text `@everyone`
2. Use the pasta

**Expected behavior**
It doesn't annoy 1000+ people.
`@everyone` and all mentions including `@here`, roles and people are escaped with a zero-width character or something.

**Comment by velddev** [comment]
It doesn't ignore permissions, you gave her the permission to ping everyone. Pings will be no longer accepted though soon.

**Comment by dct0** [comment]
Oh yeah what I meant was that it ignores the permissions of the user that executed the command, not the bot. Sorry if I was unclear. :)

**Comment by velddev** [comment]
Ah, yes. Sadly I do not track whether a pasta does or does not have pings in them as of now. I'll add this to the 0.7.1 project though.
