### ISSUE TITLE
Wont Divorce.

### ISSUE THREAD

**Issue by Asugimstcin-AustinMemeLord** [veldlabs/miki-bot#496]
I Want too divorce this user, But It Isn't letting me divorce. it shows up when i type >divorce and when it tells me too type the number 1 i do, and it does nothing. any suggestions?

**Comment by adv0catus** [comment]
Hey, thanks for the ticket! This issue has already been reported here: https://github.com/Mikibot/Miki/issues/481

But you can still try and divorce. Just type the number for the person you want to divorce a bunch of times until Miki divorces you. If it doesn't work after a few minutes, do the command again.

Not ideal, I know, but it works for now. :) Thanks again.
