### ISSUE TITLE
>requestfeature won't send request to the Miki server if on different shards

### ISSUE THREAD

**Issue by xialight** [veldlabs/miki-bot#5]
It will say you request the request but it won't show on #dev_idea_feed if on a different shard of Miki server.

**Comment by velddev** [comment]
> request feature has been removed until i get a better system

**Comment by rosieneko** [comment]
Hi Veld, this is still an issue; requestfeature has not been removed as a command that people can use. Is this disabled or not?

E.g., now it doesn't work when even same shards; it seems it might be iffy.

**Comment by velddev** [comment]
It's probably undone when the git failed. However it's no longer a big problem as miki doesn't crash on it.

**Comment by Aliya515** [comment]
> requestfeature works on the Miki server though.

**Comment by velddev** [comment]
Yes. As stated it only malfunction on _other_ shards.

**Comment by Aliya515** [comment]
Nono, I'm on servers with the same shards as the Miki server yet the requestfeature won't add to #de_idea_feed, as Rosie mentioned earlier.

**Comment by velddev** [comment]
Yes. This is discord caching your >playing. You think your on the same shard, but you aren't

**Comment by Aliya515** [comment]
OOOH, that makes sense. Thank you!

**Comment by rosieneko** [comment]
Should there be something set to limit the usage of requestfeature to Miki server, since that would guarantee that the command goes through?

Because otherwise people think the ideas are going through when they aren't :p

**Comment by velddev** [comment]
I might run it via pm.

**Comment by velddev** [comment]
This feature has been removed in 0.1.9
