### ISSUE TITLE
Divorce Issues

### ISSUE THREAD

**Issue by KneikKne** [veldlabs/miki-bot#500]
**Describe the bug**
I can not divorce players, Pressing two, using the name they're registered by or the name they currently have doesn't work.
**To Reproduce**
1. Typing !divorce (because the prefix was changed)
2. See options for being able to divorce
3. Type !divorce 2 as told
4. Nothing occurs

**Expected behavior**
I expected to be able to divorce player

**Screenshots**
![image](https://user-images.githubusercontent.com/42630179/44502482-825f3800-a646-11e8-88ca-d7c27a888ffe.png)

**Additional context**
I've looked online, and cant find anything

**Comment by adv0catus** [comment]
This has been reported https://github.com/Mikibot/Miki/issues/481 but thank you for opening this issue.
