### ISSUE TITLE
>syncname does not work

### ISSUE THREAD

**Issue by 404-unknown** [veldlabs/miki-bot#502]
**Information to problem**
Username has been changed and syncname won't change it when viewing a person whos user is married to in their Miki profile. It stayed the same as it was before, not into the current one in theirs. A few weeks passed and it still does not work.

**To Reproduce**
1. Go to settings and change your discord username
2. Command >syncname and it'll say it "OKAY I've synchronized your current name to Miki's database!"
3. Command to see the profile of whoever you're married to (>profile [@their username])
4. See error of your past username there, it doesn't change your user when you view someone else's marriages

**Expected behavior**
Miki is supposed to change the user even in the person's profile whoever the user is married with.

**Screenshots**
Current username (not nickname, actual username)--> bla
![syncname miki 1](https://user-images.githubusercontent.com/42669024/44575066-20432780-a759-11e8-93ec-6599b002c385.png)

Past username--> Unknown.404
![syncname miki 2](https://user-images.githubusercontent.com/42669024/44575111-34872480-a759-11e8-9d4f-3f911f3d5a74.png)

**Comment by adv0catus** [comment]
Thank-you for reporting this bug, it’s really appreciated, but we have an issue open for this here https://github.com/Mikibot/Miki/issues/387

Have a good day. :)
