### ISSUE TITLE
Streak Restore item.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#506]
**Is your feature request related to a problem? Please describe.**

Losing a streak makes me sad. :(

**Describe the solution you'd like**

A consumable item that restores the lost streak.

**Comment by velddev** [comment]
There's no way at the moment to realize this without overhauling the caching logic.

**Comment by velddev** [comment]
Ideas are no longer supposed to be here, please add this idea to https://suggestions.miki.ai
