### ISSUE TITLE
leveling

### ISSUE THREAD

**Issue by miyulp** [veldlabs/miki-bot#507]
just.. yknow throwback to when people got mekos for leveling up in a server 😔🤙 b-bring it back maybe?

**Comment by velddev** [comment]
Hi Miyulp!

Sadly, levelling giving mekos gave a lot more issues at face-value than I originally had thought of. This is definitely a goal I'm planning to set up, however I will plan a lot more in depth on why the previous system introduced a lot more issues for me to run around with.

For now there's no plans to revive it, but not soon.
