### ISSUE TITLE
Word filter

### ISSUE THREAD

**Issue by EternalBlueFlame** [veldlabs/miki-bot#508]
**Describe the solution you'd like**
Ability for a server to have a list of words that miki will automatically censor if possible, or remove the offending message entirely, with an option to warn the user.

**Describe alternatives you've considered**
I've used the versions available in Mee6 and Dyno and they do the job.

**Additional context**
Primarily this would be intended for a profanity filter, and/or to just filter out other potentially unwanted words.

**Comment by velddev** [comment]
Hey, that's a nifty idea, I'll start looking into it whenever I finish the backend update :)

**Comment by velddev** [comment]
Ideas are no longer supposed to be here, please add this idea to https://suggestions.miki.ai
