### ISSUE TITLE
>roulette not working

### ISSUE THREAD

**Issue by FateXBlood** [veldlabs/miki-bot#509]
>roulette does not seem to work anymore. We tried checking it from the help command as well but it does not respond.

**Comment by adv0catus** [comment]
It works on my private server. How are you using the command? If you use `>showmodule fun` does roulette show as enabled or disabled? Keep in mind that `>showmodule` works on a per-channel basis.

**Comment by FateXBlood** [comment]
It is showing enabled but is still not working. :/ 
I used roulette command in bot-spam and other channels and there's no luck.

**Comment by FateXBlood** [comment]
I type the command like this

">roulette Good Person"

**Comment by adv0catus** [comment]
Try `>roulette`

Nothing else before the `>` and nothing else after the `>roulette` just do `>roulette`.

**Comment by adv0catus** [comment]
This should be working. If not, will re-open.

**Comment by awsomeaamir** [comment]
has >roulette been removed

**Comment by velddev** [comment]
oh ye
