### ISSUE TITLE
No Bot informations

### ISSUE THREAD

**Issue by IvanBaroni12** [veldlabs/miki-bot#510]
Hello!
My name is Ivan and I came here to ask for help about something. My friend is going through a recent problem only in her account, where in some Bots the information does not appear when using the commands. In PC, mobile and browser this problem happens and we are not understanding the reason, because only in that account has occurred this, Is there any way to fix it? Thanks for the help. (Sorry for english, i'm use Google Translate)

![help](https://user-images.githubusercontent.com/44406037/47367913-079eb180-d6b7-11e8-9384-ab6a69ec0fa7.png)

**Comment by velddev** [comment]
Hi Ivan, please give miki the ability link external embeds 👍

**Comment by IvanBaroni12** [comment]
Thanks for the help Mike! It worked!
