### ISSUE TITLE
unsuccessful >acceptmarriage message

### ISSUE THREAD

**Issue by bekaertruben** [veldlabs/miki-bot#511]
![image](https://user-images.githubusercontent.com/43539018/48253328-519dcc00-e407-11e8-9cf7-1ebdffab0514.png)
Not really a bug, but this message should be "**username**, you do not have enough marriage slots ..."
For future reference, where should I post issues like this, cause I believe this shouldn't go on the GitHub.

**Comment by velddev** [comment]
If you want, you can join the translation team for english where these can be fixed here. I'm not a native english-speaker, and especially during times where I work long hours my writing isn't always the best.
https://poeditor.com/join/project/FIv7NBIReD

**Comment by adv0catus** [comment]
I tried to find that string in search and have looked through all the POEditor strings and didn't see it. :(

**Comment by bekaertruben** [comment]
Huh, strange... Could it be hardcoded perhaps?
'Tin' is the user's name, so if you searched that, you wouldn't get anything.
I may join the translation team, but I won't always be able to put a lot of time into it.

**Comment by adv0catus** [comment]
I didn't search by the username because it shows up as a `{0}` variable in the strings. I looked for `:(` and `slots` and went through all the strings manually.

**Comment by velddev** [comment]
To come back to this issue. It has been added to the resources and will be pushed as `{0}, you do not have enough marriage slots to marry another person!` in the next update.

See fcaf5cb for commit details

**Comment by velddev** [comment]
It's live
