### ISSUE TITLE
Selfhosting thread

### ISSUE THREAD

**Issue by velddev** [veldlabs/miki-bot#512]
So over the last year or so, the demand for a self-hostable Miki was getting more and more in demand. This has turned some of my priorities into a different direction and therefore I have opened this thread. There are three ways this can go right now
* Make a docker image and redistribute it
* Make a selfhosted version as an option in the current miki
* Make startup contexts.

For all of these I will briefly explain what they mean. So to begin:

A docker image is somewhat of a disk file that loads everything it needs in a 'seperate' system on a computer (lets say having a virtual machine in windows). and will always work due to the environment being similar anywhere. But, there are some problems with it, for windows users, this means you need a Windows 10 (or similar) Pro+ license, which is very uncommon for regular use.

A selfhosted version as an option is simply adding a `"selfhosted": true` in Miki's config files, and let her load from this, this does mean that additional code will enlarge the program, which is growing at an infinite pace already.

My personal solution would be to create startup contexts, this would mean that the application sets up a context to Discord, Memory, and databases accordingly, and the bot itself will accept either regardless and run from it.

Please let me know what you think about these approaches, and lets have a discussion about this.

**Comment by LovingMelody** [comment]
I'm guessing most people wanting to self-host aren't wanting to go through multiple steps to self-host Miki. I'd say just go with docker, we can have two Dockerfiles (one specifically for arm) and that could simplify the process. Anyone wanting to self host and don't have Windows 10 pro can just get a raspberry pi and host that way.
