### ISSUE TITLE
>reminder -list says no reminders are active.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#513]
**Describe the bug**

I set a reminder then checked my reminder list and Miki said I had no reminders active. Haven't confirmed if the reminders weren't actually set and Miki won't remind me of it (because the reminders are several hours into the future).

**To Reproduce**

1. Set a reminder.
2 Use `>reminder -list`
3. No reminders active.

**Expected behavior**

A list of active reminders.

**Screenshots**

![](https://i.imgur.com/6XNHp6F.png)

**Comment by velddev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [>reminder -list says no reminders are active](https://trello.com/c/KYekJU0J/363-reminder-list-says-no-reminders-are-active)

**Comment by adv0catus** [comment]
A 10 minute and 1 second both one time and recurring reminder worked, neither appeared on the list, though. They were assigned IDs, though. Clearing a one time reminder with ID works.
