### ISSUE TITLE
Pastas made by deleted Discord users cannot be deleted by anyone else?

### ISSUE THREAD

**Issue by Ironicgenocide** [veldlabs/miki-bot#518]
I wanted a specific pasta made by a user who is deleted (was a mutual of mine, so I was aware of them deleting their Discord account) deleted, but of course it wouldn't work since it's not my pasta. However, the user isn't there anymore.

**Comment by adv0catus** [comment]
Contact the staff on the Miki Support server and they will review the pasta.

https://discord.gg/39Xpj7K

Pastas are global (work on all servers, not just the one it's made on) so it's a tough thing to handle deletions. As of now, at least, the pasta owner and the developer are the only ones able to delete pastas.
