### ISSUE TITLE
>ship command doesnt work and with a specific user 

### ISSUE THREAD

**Issue by mankouwu** [veldlabs/miki-bot#523]
When someone tries to >ship with this specific user, Miki returns the below screenshot. Same happens when that user tries to use >ship with anyone. All other users do not experience this issue. 

![image](https://user-images.githubusercontent.com/47404521/52382523-9e636400-2a43-11e9-910d-cf8a7a68f49a.png)

**Comment by adv0catus** [comment]
Does Miki have the embed permission?

**Comment by velddev** [comment]
make sure to use `>syncavatar` for miki to be able to use your avatar
