### ISSUE TITLE
make miki say anything bug

### ISSUE THREAD

**Issue by awsomeaamir** [veldlabs/miki-bot#524]
This bug allows a user to manipulate miki bot to say anything

**To Reproduce**
1. Go to any channel where miki is allowed
2. type ">calc 'what you want miki to say '   "
3. and miki will send that message that message 

**Expected behavior**
miki can be made to say anything the user wants it to say 

![image](https://user-images.githubusercontent.com/15050976/53246153-c8559100-36a7-11e9-94c8-7213378260b9.png)

**Comment by Xetera** [comment]
I'll have a look at this, thanks.

**Comment by velddev** [comment]
I don't believe this is a bug, it is a string in the interpreter.
