### ISSUE TITLE
all of the achievements not showing 

### ISSUE THREAD

**Issue by Maxavage** [veldlabs/miki-bot#526]
**Describe the bug**
Despite having alot of achievements only 2 show up 

**To Reproduce**
1. >profile

**Expected behavior**
show all your achievements on the bottom.

**Comment by adv0catus** [comment]
I have a significant number of achievements and I'm not having the same issue:

![](https://i.imgur.com/1q21F8g.png)

What shows up when you use the `>achievements` command?

**Comment by velddev** [comment]
I think this relates to the stacking achievements, which overlap eachother. Check the achievements wiki page on achievements that have multiple tiers 👍
