### ISSUE TITLE
date is set to 1/1/01

### ISSUE THREAD

**Issue by sasukouchiha** [veldlabs/miki-bot#528]
For some reason the date is not working for my profile at all.  It shows my achievements and join date as 1/1/01, but displays the correct date with the marriages.

**To Reproduce**
1. Go to >profile
2. Scroll down to bottom of profile for join date.
3. See error

**To Reproduce**
1. Go to >achievements
2. See error

**Expected behavior**
I expect it to show a date at least after my date of joining discord, not years before I even joined

**Screenshots**

![achievements](https://user-images.githubusercontent.com/48902541/54899445-39a28280-4ea6-11e9-9991-318ceef4de46.png)
![profile](https://user-images.githubusercontent.com/48902541/54899448-3c9d7300-4ea6-11e9-9056-599af567a83d.png)

**Comment by sasukouchiha** [comment]
I have found 14 others on my server that the same is true for them.

**Comment by sasukouchiha** [comment]
Just gained 2 new achievements and it still lists as 1/1/01
![gained achievements 3-26-19](https://user-images.githubusercontent.com/48902541/54983898-13ebab00-4f84-11e9-8bce-e748798035cc.png)
![profile 3-26-19](https://user-images.githubusercontent.com/48902541/54983903-1817c880-4f84-11e9-8c4d-6d89b6bd3921.png)
![achievements 3-26-19](https://user-images.githubusercontent.com/48902541/54983908-1a7a2280-4f84-11e9-88d9-fef2236b7f6c.png)

**Comment by velddev** [comment]
Hmm... Odd, I'll look into it

**Comment by sasukouchiha** [comment]
thank you

**Comment by GerardSmit** [comment]
As today this issue isn't fixed yet:

![image](https://user-images.githubusercontent.com/2109929/59194786-6ce1dd00-8b8a-11e9-9a05-0e4f99026ae7.png)

I've received the achievement Lenny and Shipgirl today and both are showing 1/1/01

**Comment by Zenulous** [comment]
This is fixed.

![image](https://user-images.githubusercontent.com/45333650/91982933-3e21ca80-ed2b-11ea-80cf-dcdf16892619.png)
