### ISSUE TITLE
Miki won't kick even with permission.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#529]
**Describe the bug**

Miki says she needs the `Kick Members` permission when you try to use the `>kick` command. But she has it in the auto-generated Miki role and that hasn't been modified.

**To Reproduce**
1. Invite Miki to your server.
2. Attempt to kick someone.

**Expected behavior**

Miki to be able to kick when she has the permissions to do so.

**Screenshots**

Her having the `Kick Members` permission on her auto-generated Miki role:

![](https://i.imgur.com/fJITKrH.png)

Not being able to kick a user:

![](https://i.imgur.com/DDEQoJC.png)

**Comment by velddev** [comment]
This is a backend bug for Miki.Discord where it does not synchronize after initial setup

**Comment by velddev** [comment]
This hasn't been fixed yet.
