### ISSUE TITLE
The Ranks are not updating in >profile and >exp

### ISSUE THREAD

**Issue by Sworduster** [veldlabs/miki-bot#531]
**Describe the bug**
The global ranks for xp are not updating in `>profile` and `>exp`

**To Reproduce**

1. `>top` shows your actual ranking  
2. `>profile` and `>exp` ranks are frozen for a while

**Comment by adv0catus** [comment]
I think it's a caching thing where it's not updated right away to save processing power for Miki.

**Comment by velddev** [comment]
They are indeed cached, and update once a day.

**Comment by Sworduster** [comment]
but its been a couple of days 
i am actually rank #510 while its still showing my rank from a week ago #600

**Comment by night0119** [comment]
The Ranks are not updating in >profile and >exp, they are frozen, since i was #30052, now i am the #17380, i alredy level up, like .. 30 levels or more, and still glitched. :(
