### ISSUE TITLE
Miki does not tell when you when you dont have enough mekos to buy marriage slots

### ISSUE THREAD

**Issue by Sworduster** [veldlabs/miki-bot#533]
**Describe the bug**
Miki does not tell you when you have not enough mekos to buy a marriage slot

**To Reproduce**
1. Try to buy a marriage slot while not having enough mekos for it.

**Expected behavior**
Miki tells you your mekos are insufficient.

**Comment by velddev** [comment]
Should be fixed with the latest patch
