### ISSUE TITLE
Daily Limit

### ISSUE THREAD

**Issue by jevido** [veldlabs/miki-bot#537]
The daily limit is too low. Me and a friend of mine have been going at it for 105 days now. But since day 100, we have reached a limit of 2,100 mekos a day. 
I think this is a bit weird to have as a limit. I'd rather have no limit at all. (since it's only a 20 mekos a day increase) or have a nice figure as limit.

What is up with this?

**Comment by velddev** [comment]
Hey, the limit is 100 days in sequence, after that you've maxed the daily value. from this point on the only way to further increase your daily is reserved for donating and upcoming features such as buffs, upgrades and such.
