### ISSUE TITLE
Slapahoe

### ISSUE THREAD

**Issue by Slapahoe** [veldlabs/miki-bot#539]
Will not let me play the games on discord >ship @

**Comment by velddev** [comment]
Make sure both people use `>syncavatar` beforehand.

**Comment by Slapahoe** [comment]
Its still not working

Sent from Yahoo Mail on Android 
 
  On Thu, May 16, 2019 at 2:01 AM, Mike<notifications@github.com> wrote:   
Make sure both people use >syncavatar beforehand.

**Comment by adv0catus** [comment]
Both people need to use the command. Have they?

**Comment by Slapahoe** [comment]
Miki will not work for me...why in the fun commits will it not work for only me?

**Comment by adv0catus** [comment]
Providing more troubleshooting information and screenshots is a great way to help with the resolution process. :)

**Comment by Slapahoe** [comment]
![Screenshot_2019-05-26-21-35-59](https://user-images.githubusercontent.com/50689140/58395695-5d955800-7ffe-11e9-8a38-c67218f35e15.png)
This is what it keeps doing to me.

**Comment by adv0catus** [comment]
You need to mention and tag the person or use their User ID.
