### ISSUE TITLE
Achievement bug

### ISSUE THREAD

**Issue by Batuhanalperen** [veldlabs/miki-bot#546]
**Describe the bug**
I have 5 achievements but I don't have the "Achiever" achievement.
**To Reproduce**
1. Go to '>profile <@257181310353801216>'
2. Look my achievements and see the bug

**Expected behavior**
I should have Achiever achievement.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/40668308/61251907-77ccf600-a764-11e9-9b80-39e0242b6a88.PNG)

**Comment by ironwolftamer** [comment]
I have the same issue with the underachiever achievement and some other ones. For instance, I have voted quite a few times for the miki bot yet I have no voter achievement. I'll attach proof and before anyone asks about the voting, yes I have made sure I am using the right account for the vote, I get the mekos from it and can even work up a streak.
![MikiProfile](https://user-images.githubusercontent.com/36218526/70207428-5c9d5b80-16f0-11ea-9052-9010143f3c8f.PNG)
![MikiVote](https://user-images.githubusercontent.com/36218526/70207432-6030e280-16f0-11ea-813e-96d49c018c91.PNG)
This is only 4 of the 8 times total that I've voted.

**Comment by velddev** [comment]
@ironwolftamer to address the levelling one; you seem to already obtained the achievement for level 5 from a different server. as the achievement icon is the this: 
<img src=https://user-images.githubusercontent.com/13852840/70222438-5f2c9f00-174a-11ea-92d0-85d6828549f2.png>

**Comment by ironwolftamer** [comment]
> @ironwolftamer to address the levelling one; you seem to already obtained the achievement for level 5 from a different server. as the achievement icon is the this:
> ![](https://user-images.githubusercontent.com/13852840/70222438-5f2c9f00-174a-11ea-92d0-85d6828549f2.png)

Yeah I had realized that after I posted my initial comment, so that's why I edited it. It was my fault for that one.
