### ISSUE TITLE
Leaderboard command (click me!) link redirects nowhere!

### ISSUE THREAD

**Issue by Batuhanalperen** [veldlabs/miki-bot#547]
**Describe the bug**
Leaderboard command (click me!) link redirects nowhere!

**To Reproduce**
1. Go to '>lb'
2. Click on 'Embed's Author Link'
3. See error

**Expected behavior**
Usable website url

**Screenshots**
![mikibug2](https://user-images.githubusercontent.com/40668308/61579774-0d280b80-ab12-11e9-9611-0e5bf101ad83.png)

![mikibug1](https://cdn.discordapp.com/attachments/485127642790625282/602141871531229214/unknown.png)

**Comment by velddev** [comment]
Yeah that's right. We restructured the website to be more performant and responsive for future endavours
