### ISSUE TITLE
Move configuration to .env

### ISSUE THREAD

**Issue by velddev** [veldlabs/miki-bot#551]
Due to some complications with .json configuration files and efcore it would be very beneficial to have either configuration on the database and connect to it through .env or move everything to an env space.

@Xetera @GerardSmit @Niputi I'd love what you guys think

**Comment by GerardSmit** [comment]
👍

With this change it'll also be easier to create a Docker image (which is a stale issue/discussion: https://github.com/Mikibot/bot/issues/512)

**Comment by exsersewo** [comment]
I'd assume with how it works it would make sense to have it in the database, however that comes with a single point of failure argument. Though with having everything as an env var, ensuring everything is mirrored correctly would be a huge issue. I, personally, would go for the database option.

**Comment by velddev** [comment]
> With this change it'll also be easier to create a Docker image (which is a stale issue/discussion: #512)

Absolutely correct! fewer things to map to docker is better.

>I'd assume with how it works it would make sense to have it in the database, however that comes with a single point of failure argument.

This is a minor issue however; I think for this failover nodes are a great solution. I would definitely also recommending to run failover tests on infra-level to make sure failovers are always consistent.

**Comment by Niputi** [comment]
![image](https://user-images.githubusercontent.com/7137178/62652562-f67c1400-b95b-11e9-8575-03e14de5db5e.png)
