### ISSUE TITLE
the weekly tool-tip showing >guildnewrival wrong

### ISSUE THREAD

**Issue by Sworduster** [veldlabs/miki-bot#557]
**Describe the bug**
when you do >guildweekly it tells you to do >guildrival instead of >guildnewrival

**To Reproduce**
1. >weekly
2. >guildrival
3. nothing happens

**Expected behavior**
>weekly error message saying >guildnewrival instead of >guildrival
or 
>guildrival being an alias to >guildnewrival

**Comment by adv0catus** [comment]
I'm not sure what the problem with this is? I could be remembering wrong, but from what I recall and the guild_accounts module, `>guildrival` isn't a command. The help text for `>weekly` gives the command's proper name and doesn't mention `>guildrival` at all.

![image](https://user-images.githubusercontent.com/10149775/66114979-e9675400-e59d-11e9-9be3-8cc937a0753b.png)

`>guildnewrival` is a completely different admin-only command that probably shouldn't be used often and as said, can only be used by server admins.

**Comment by Sworduster** [comment]
we receive a lot of issues about it, it happens when someone with his new server tries to do `>weekly` for the first time

he gets a message telling him to do `>guildrival`

which is wrong

**Comment by velddev** [comment]
Seems to have been fixed in staging
