### ISSUE TITLE
Black Jack hit error

### ISSUE THREAD

**Issue by YolosFinest** [veldlabs/miki-bot#558]
**Describe the bug**
When gambling in Blackjack I attempted to >BJ hit, instead of hitting and dealing me an additional card the dealer started receiving cards instead. 

**Expected behavior**
Expected an additional card to be dealt to me in Blackjack. 

**Screenshots**
![BDAAF8B1-CC0E-48A0-B854-9635200E8D38](https://user-images.githubusercontent.com/56095583/66085432-2819f180-e53f-11e9-926e-d4585e16ea76.jpeg)

**Comment by NoahtheDeveloper** [comment]
where is that at??
