### ISSUE TITLE
Can't get 100% from >ship

### ISSUE THREAD

**Issue by GudilinAC** [veldlabs/miki-bot#559]
**Describe the bug**
You can't get 100% from `>ship`. Code:
https://github.com/Mikibot/bot/blob/b6c0cf3cb6df124efc158b27935aff7e75c64cad/Miki/Modules/FunModule.cs#L776 According to [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.random.next?view=netframework-4.8#System_Random_Next_System_Int32_System_Int32_) second value is exclusive, so you can't get it.

**Comment by velddev** [comment]
This is true, but intentional. I've planned a special marriage integration with ships to gain 100%.

**Comment by adv0catus** [comment]
It is possible now.

![](https://i.imgur.com/VLRMo5l.png)
