### ISSUE TITLE
Blackjack bug

### ISSUE THREAD

**Issue by Elekikiss** [veldlabs/miki-bot#560]
![image](https://user-images.githubusercontent.com/19418546/69902037-f3a79380-133d-11ea-8e2d-ab55fe76b0b0.png)

I was at A A 2 8 (12) when I took a 3rd hit; the card went to Miki instead of myself, however, and made her bust.
I tried reproducing the bug, and I confirmed that the player IS supposed to be able to get 5 cards (and bust), and that Miki doesn't automatically hit if the player has 4 or more cards. (confirmation games below)
I am unsure why the last card went to Miki OR if there was some kind of time-out system that made Miki start to take her turn, and she ended up bugging out on the decision tree due to the double Ace. Whichever is the case, there is some kind of a bug being highlighted by that game, which I sadly cannot reproduce reasonably (because a double A is rare).

![image](https://user-images.githubusercontent.com/19418546/69902276-74678f00-1340-11ea-8991-79d604dc16c2.png)

**Comment by Elekikiss** [comment]
It appears this report is a duplicate of Bug #558 
The things in common is that we both had 4 cards, and that we started with a double ace.

**Comment by velddev** [comment]
Is this still happening on staging? Could you verify for me @Elekikiss? (Staging bot can be found in Miki Development in #info on the miki discord)
