### ISSUE TITLE
Bug: >marry shows invalid documentation of how to decline a marriage.

### ISSUE THREAD

**Issue by Pao-Lumu** [veldlabs/miki-bot#561]
**Describe the bug**
Marriage embed states that the proper way to decline a marriage proposal is with `>declinemarriage <@user>`

**To Reproduce**
Step 1. Have someone attempt to marry you. 
Step 1.5. Observe embed.
Step 2. type `>declinemarriage <that users @-tag>` 
Step 3. 

**Expected behavior**
The person who tagged me should get shot down.

**Screenshots**
no.

**Additional context**

The following is to be read in the most British accent you can imagine.

> At 5:50 AM UTC, on the Second of the month of December, Two-Thousand and Nineteen, a man, the Right Honourable `@darkz#4841`, offered to take my hand in marriage.
> This advance was not merely unsolicited, it was performed in the most uncouth of places. (The Forum for Digital and Computational Programming, henceforth referred to as '#dev-stuff')
> 
> Repulsed and abhorred by this impropriety, I immediately sought to refute it, taking the proper, documented methods provided by Her Royal Highness, Queen Miki, Sovereign of the Order of Weeha Bu. However, when my plea was heard and the response given, it was a form, with but two names, instructions to specify which proposal I wished to refute, and a return address.
> 
> In a fit of rage, I spat at the documents, cursing this failure of the system on the laws of the land, as laid out by the Prime Minister, the Right Honourable Mike. And so, I beseech the Parliament, please... remove this needless process for refusing marriage to a would-be suitor.

~~You bet your ass that was fun to write~~

**Comment by velddev** [comment]
I kinda removed the <@user> for now until we find a better solution.
