### ISSUE TITLE
IContext consistency reeee

### ISSUE THREAD

**Issue by exsersewo** [veldlabs/miki-bot#563]
Move all `IContext e`s to be `IContext ctx` as per your request ;)

https://clips.twitch.tv/CharmingSassySmoothieCclamChamp

**Comment by velddev** [comment]
wegvpjoapwedvojjpokwgejopgwejpowegjopwegjogpwejopgwegwejfpojopgwewjegopjpogwewjegopjopgwe 💢 wegvpjoapwedvojjpokwgejopgwejpowegjopwegjogpwejopgwegwejfpojopgwewjegopjpogwewjegopjopgwe 💢 wegvpjoapwedvojjpokwgejopgwejpowegjopwegjogpwejopgwegwejfpojopgwewjegopjpogwewjegopjopgwe 💢 wegvpjoapwedvojjpokwgejopgwejpowegjopwegjogpwejopgwegwejfpojopgwewjegopjpogwewjegopjopgwe 💢 wegvpjoapwedvojjpokwgejopgwejpowegjopwegjogpwejopgwegwejfpojopgwewjegopjpogwewjegopjopgwe 💢 wegvpjoapwedvojjpokwgejopgwejpowegjopwegjogpwejopgwegwejfpojopgwewjegopjpogwewjegopjopgwe 💢

**Comment by velddev** [comment]
oops

**Comment by velddev** [comment]
This is a professional organization.

**Comment by exsersewo** [comment]
Then be professional ;)
