### ISSUE TITLE
Can't deposit in guildbank

### ISSUE THREAD

**Issue by Shiroi-shi** [veldlabs/miki-bot#571]
**Describe the bug**
Trying to deposit in guildbank just show the basic >guildbank help message

**To Reproduce**
1. Do >guildbank deposit <nbr>
2. It just show the >guildbank basic message
3. ">guildbank balance" is still at 0 mekos

**Expected behavior**
Add mekos to the guild bank

**Comment by velddev** [comment]
Fixed in 2020.1.287
