### ISSUE TITLE
You can't buy backgrounds

### ISSUE THREAD

**Issue by air-sys** [veldlabs/miki-bot#575]
**Describe the bug** 
Wellllll you cant buy backgrounds

**To Reproduce**
1. Type in >buybackground 25 etc
2. The error message background does not exist will come up.

**Expected behavior**
The background do exist but for some reason you can't buy them. The background s error message should come up when you try this for yourself.

**Comment by velddev** [comment]
This is because of the current deployment not including the resource files. Need to look into this in the future.

Maybe if @exsersewo has time, could you check if there's a way to include this in the MSBuild pipeline?

**Comment by velddev** [comment]
Resources load now; I haven't checked why it shows only background #0 now.

**Comment by velddev** [comment]
Has been resolved now.
