### ISSUE TITLE
">Whois" Display incorrect roles

### ISSUE THREAD

**Issue by Zephy-o** [veldlabs/miki-bot#576]
**Describe the bug**
>whois Displays all available roles under the users "Roles" when it should only display the roles the user has.

**To Reproduce**
1. use >whois @user
2. Roles do not match roles on the users profile

**Expected behavior**
The command should display the correct roles

**Screenshots**
![image](https://user-images.githubusercontent.com/49200495/72028152-6d099e80-3279-11ea-8a64-de2bd5f42602.png)

**Comment by air-sys** [comment]
Oh yeah, I tried for myself too and same results

**Comment by velddev** [comment]
Fixed in 2020.1.288
