### ISSUE TITLE
Pastas don't work

### ISSUE THREAD

**Issue by air-sys** [veldlabs/miki-bot#577]
**Describe the bug** 
Pastas don't work

**To Reproduce**
1. Make a pasta
2. Try and run it
3. See error

**Expected behavior**
You can't load pastas achievements oh shit waddup and shipgirl don't work

**Comment by air-sys** [comment]
Update: pastas don't work at all you can even load >mypasta

**Comment by velddev** [comment]
Fixed in 2020.1.280
