### ISSUE TITLE
Rps (rock paper scissors) doesn't work 

### ISSUE THREAD

**Issue by Makafa15** [veldlabs/miki-bot#579]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Zephy-o** [comment]
The command is working however it is not displaying the "Something Went wrong , Enter an amount" error message when you do ">rps r" with no bet amount.

**Comment by velddev** [comment]
No further information given, can't do anything with this.
