### ISSUE TITLE
>osu doesn't work

### ISSUE THREAD

**Issue by air-sys** [veldlabs/miki-bot#582]
**Describe the bug**
>Osu doesn't work

**To Reproduce**
1. Type >osu [insert your ign or a random user here]
2. No response

**Expected behavior**
You won't get a response

**Additional context**
I think all the gaming category is broken too
So Veld when you read this be sure to check that section out too plz

**Comment by air-sys** [comment]
Gaming category is where >osu is categorised btw

**Comment by exsersewo** [comment]
For more information:

This command isn't available due to live version on https://lemmmy.pw/ being deprecated.
P.S: The [osusig generator is open source](https://github.com/tmpim/osusig) and could be rehosted on Miki's API stack? @velddev

**Comment by velddev** [comment]
Serving PHP and maintaining it sucks though

**Comment by exsersewo** [comment]
Isn’t that where docker would come in and help out with maintaining and serving it?

**Comment by velddev** [comment]
https://github.com/velddev/dotnet-osu-api will leverage the current changes.

**Comment by velddev** [comment]
has been fixed with the new embeds
