### ISSUE TITLE
Full report if every cmd on miki

### ISSUE THREAD

**Issue by air-sys** [veldlabs/miki-bot#583]
So please keep note, this will be update A LOT, as I find more things. I will progress a lot. Let me explain how I'll be presenting this, I'll show every section of cmds. You know that section when you type >help? Those. Here I start. I will add more to this later keep that in mind please, just before I go if you have any counter arguments please leave them in the comments.
All of Actions Section Works🎉
Experimental section is Dev only so i can't test those.
Fun section has a few broken cmds, here's a list, >dog, >gif, >img.

**Comment by velddev** [comment]
Preferably seperate them per issue, so I can easier close them :-)

**Comment by air-sys** [comment]
Got it
