### ISSUE TITLE
Slots only paying out winnings

### ISSUE THREAD

**Issue by Yodo01** [veldlabs/miki-bot#586]
**Describe the bug*
Slots all returns the profits only

**To Reproduce**
1. \>slots all
2. Win
3. See that the profits are the only thing that you won.

**Expected behavior**
Win profits and get initial balance back

**Screenshots**
![Screenshot (145)](https://user-images.githubusercontent.com/60075647/72687714-a8ed0100-3ace-11ea-9342-5357593d2478.png)

**Comment by velddev** [comment]
Fixed in e08351f
