### ISSUE TITLE
Local ranking not correct and probably going in reverse

### ISSUE THREAD

**Issue by Shiroi-shi** [veldlabs/miki-bot#588]
**Describe the bug**
Getting a worst local rank after getting some xp without having anybody else talking in the server

**To Reproduce**
1. Do >profile and check your rank (mine was #102)
2. Gain some xp
3. Do >profile again
4. Ranking got worst (I went from #102 to #103)

**Expected behavior**
Ranking is supposed to go lower

**Screenshots**
![image](https://user-images.githubusercontent.com/15214426/72818567-fe124980-3c6b-11ea-844a-5243d52673d5.png)

**Comment by velddev** [comment]
oh yea, I didn't write tests yet; will be patched tonight

**Comment by velddev** [comment]
Should've been fixed
