### ISSUE TITLE
calc command not pruning @everyone mentions from the result

### ISSUE THREAD

**Issue by exsersewo** [veldlabs/miki-bot#590]
**To Reproduce**
1. Do `>calc [something that results in @[]everyone]`
2. It results in "@[]everyone" and could potentially result in a ping in the server with permissions

**Expected behavior**
@[]everyone should be pruned/nonpingable

**Screenshots**
![image](https://user-images.githubusercontent.com/25526843/73396395-30a9eb00-42d9-11ea-83cb-9163cc65eb32.png)

**Comment by velddev** [comment]
solved in 4cdfa41
