### ISSUE TITLE
Rps bug

### ISSUE THREAD

**Issue by Bunny-Boo** [veldlabs/miki-bot#592]
**Describe the bug**
I lost in >rps and didn't lose any mekos after it.

**Expected behavior**
It was Scissors vs Paper and I was supposed to win and gain mekos.

**Screenshots**
![Screenshot_20200212-105509_Discord](https://user-images.githubusercontent.com/59715817/74324871-000d8b00-4d88-11ea-9b54-f1b998f4a7e6.jpg)

**Comment by velddev** [comment]
Resolved this issue
