### ISSUE TITLE
>showmodule(s) doesn't work.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#597]
**Describe the bug**

The commands `>showmodules` and `>showmodule` don't work. Miki ignores you.

**To Reproduce**

1. Be on the Miki Development server.
2. Type `>showmodules` and/or `>showmodule`.
3. Miki will ignore you.

**Expected behavior**

A visual breakdown of the modules for Miki and/or the individual commands in a module along with their enabled/disabled status.

**Screenshots**

![](https://i.imgur.com/0fJ2VwA.png)

**Additonal Context**

These commands work on Live Miki.

**Comment by exsersewo** [comment]
showmodules has been removed
