### ISSUE TITLE
Ship command bug

### ISSUE THREAD

**Issue by Bunny-Boo** [veldlabs/miki-bot#598]
**Describe the bug**
Bot isn't responding to command

**Expected behavior**
To show avatars and procentage of shipping

**Screenshots**
![Screenshot_20200214-162337_Discord](https://user-images.githubusercontent.com/59715817/74543920-8b347f80-4f46-11ea-9d02-3af92c6982fe.jpg)

**Comment by velddev** [comment]
Ship relies on a system that is not available in staging as of right now.
