### ISSUE TITLE
>cat and >dog bug

### ISSUE THREAD

**Issue by Bunny-Boo** [veldlabs/miki-bot#599]
**Describe the bug**
Bot is not responding to >cat command. In case of >dog command it's responding but not showing any images.

**Expected behavior**
To respond to commands and send images.

**Screenshots**
![Screenshot_20200214-193755_Discord](https://user-images.githubusercontent.com/59715817/74557973-a5c82200-4f61-11ea-866e-631a30b678ab.jpg)

**Comment by Zenulous** [comment]
Cat command works, will look into fixing dog (#624 )
