### ISSUE TITLE
miki.command hard-coded prefix functions incorrectly.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#601]
**Describe the bug**

To use the hard-coded prefix `miki.command`, you need to currently use it in the format of `miki.pingcommand` for it to function.

**To Reproduce**
1. Be in the Miki Development server.
2. Use the prefix.

**Expected behavior**

Not having to include ping in the command for it to work (or a second ping for that command to work).

**Screenshots**

![](https://i.imgur.com/P00M4pj.png)

**Comment by velddev** [comment]
Moved to https://github.com/mikibot/miki.framework/issues/16
