### ISSUE TITLE
Lonely achievement bug

### ISSUE THREAD

**Issue by Bunny-Boo** [veldlabs/miki-bot#602]
**Describe the bug**
Bot doesn't announce Lonely achievement.

**Expected behavior**
To send announcement message about achievement.

**Screenshots**
![Screenshot_20200216-142538_Discord](https://user-images.githubusercontent.com/59715817/74605441-7d0e6c80-50c8-11ea-928b-5d30a867feac.jpg)

**Additional context**
When you use >marry command on yourself you do gain the Lonely achievement.

**Comment by adv0catus** [comment]
It has never announced this achievement.

It used to give an 'error' message:

![](https://i.imgur.com/VOlvhfy.png)

But I believe the intention was that as a secret achievement, it isn't acknowledged.

**Comment by velddev** [comment]
It should announce, but you already had the achievement; see "01-07-2020"

**Comment by adv0catus** [comment]
I had just earned it right before and it didn't announce.

**Comment by Zenulous** [comment]
This will be fixed in the next release
