### ISSUE TITLE
>ask always displays the same image.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#604]
**Describe the bug**

The command `>ask` always uses the same gif as the reaction image, despite there being many options in the past.

**To Reproduce**
1. `>ask`

**Expected behavior**

A variation of images/gifs being used by Miki.

**Screenshots**

![](https://i.imgur.com/OhO2OAR.png)

**Comment by velddev** [comment]
There has never been a different image for ask
