### ISSUE TITLE
Roll Limit Bug

### ISSUE THREAD

**Issue by DandieLeon** [veldlabs/miki-bot#606]
Sometimes, before reaching the previously found 492d1 roll limit, the roll doesn't work. Like >roll 491d1 won't do anything.

**Comment by exsersewo** [comment]
@DandieLeon I’m guessing the close reasoning was due to https://status.discordapp.com/incidents/gz6nn2717gcs ?

**Comment by Drummss** [comment]
@exsersewo No, it was because the limit I stated when I use the roll command was 492d1, but because his name is longer than mine the limit for him was lower :)
