### ISSUE TITLE
>reminder bug

### ISSUE THREAD

**Issue by Bunny-Boo** [veldlabs/miki-bot#607]
**Describe the bug**
Bot doesn't send reminder in DMs.

**Expected behavior**
To send reminder message in DMs and its content.

**Screenshots**
![Screenshot_20200219-220158_Discord](https://user-images.githubusercontent.com/59715817/74876526-21600f80-5364-11ea-9a13-1de3fad997af.jpg)
![Screenshot_20200219-220215_Discord](https://user-images.githubusercontent.com/59715817/74876546-2f159500-5364-11ea-9509-a90c35b1454c.jpg)

**Additional context**
Bot can set reminder and it can show reminder list.

**Comment by Zenulous** [comment]
This works again :)
