### ISSUE TITLE
NSFW image commands return "Too many arguments for this system."

### ISSUE THREAD

**Issue by taevt-iscte** [veldlabs/miki-bot#626]
**Bug Description**
When using the commands ('Gelbooru', 'danbooru', 'rule34', 'e621', 'yandere') there is an error return message, it displays "Too many tags for this system" even when no arguments are given. Even when arguments are given the error message persists, might be an error in argument parsing.

**To Reproduce**
1. Use any of the following commands, no arguments given (>rule34)

**Expected behavior**
Possibly see a whole lot of boobies or whatever you looked for.

**Screenshots**
![imagem](https://user-images.githubusercontent.com/22846996/75633803-22186180-5c00-11ea-9569-452b1ff1a3a4.png)

**Comment by velddev** [comment]
Fixed
