### ISSUE TITLE
Miki is not responding to >guildinfo command

### ISSUE THREAD

**Issue by Bunny-Boo** [veldlabs/miki-bot#628]
**Describe the bug**
Bot is not responding to `>guildinfo` command.

**Expected behavior**
To show guild/server info.

**Screenshots**
![Screenshot_20200301-214826_Discord](https://user-images.githubusercontent.com/59715817/75633868-25fcb180-5c09-11ea-976f-13b5bba5855f.jpg)

**Comment by Zenulous** [comment]
Has been fixed a while back :)
