### ISSUE TITLE
Unicode Profile Names Unsupported

### ISSUE THREAD

**Issue by erisu** [veldlabs/miki-bot#63]
It appears that profile names containing unicode (utf-8) are unsupported. For example if the profile name is in Japanese, Miki reports `$missing-name's Profile`

![missing profile](https://cloud.githubusercontent.com/assets/1029107/22614947/d1276146-eacd-11e6-9669-17e13096a7b1.png)

**Comment by IA-Xerise** [comment]
they are, thats just a database bug that should be fixed in 1.9.9 afaik
![image](https://cloud.githubusercontent.com/assets/24828421/22614960/ac5568b0-ea58-11e6-9c94-a7820f1b1ade.png)

**Comment by IA-Xerise** [comment]
I would assume it falls under the same issue as this
https://github.com/velddev/miki/issues/38

**Comment by erisu** [comment]
Issue #38 seems to be related to updating the username after changing...
So I did not know if it was related or not. For my issue, it was not even registering my profile name to create an account.

For example:
I can trigger the `/daily` commands as many times as I want (no 24hr cool down applies to me) and it does not add anyway. My collection would always be 0.

If this is a database issue, I suspect the charset/collate encoding is not set to UTF-8 and rejects my profile name. Not sure though.

If the issue is fixed in 1.9.9 and I still have the issue... How can I check what version I am on?

**Comment by IA-Xerise** [comment]
I would assume issue 38 also ties into the lack of gaining XP and delays in creating new accounts. I myself don't code for Miki but with the limited knowledge I do have and seeing all the other issues being brought up over the profiles and names/gaining xp/earning achievements I am fairly certain the fix on 1.9.9 should resolve your issue also.

I know she supports UTF-8 or she might convert to 16 or UCS. Miki has been having some issues with her database for awhile now. My user name was in unicode at some point so i can confirm it does work.

As for how to tell what version you are on its Miki's version which shows in `>info`.
I will re-open for now. When Veld pushes 1.9.9 I will close this, If you still have issues after 1.9.9 feel free comment or drop by the support server.
