### ISSUE TITLE
Reaction commands ignore arguments

### ISSUE THREAD

**Issue by taevt-iscte** [veldlabs/miki-bot#630]
**Describe the bug**
Reaction and Action commands with arguments ignore arguments.

**To Reproduce**
1. Use >kiss @user
2. Miki kisses me, I don't kiss the user, this makes miki very naughty

**Expected behavior**
Zephy is supposed to get a kissy.

**Screenshots**
![imagem](https://user-images.githubusercontent.com/22846996/75634189-52adca80-5c03-11ea-80d0-f46cd58fbdee.png)

**Comment by velddev** [comment]
Fixed this
