### ISSUE TITLE
>exp Does not respond

### ISSUE THREAD

**Issue by taevt-iscte** [veldlabs/miki-bot#631]
**Describe the bug**
`>exp` does not return anything, no image, no message, apparently no response.

**To Reproduce**
1. Do `>exp`

**Expected behavior**
Get an image, possibly with a selected background, depicting username with tag, global exp, global level and user avatar

**Screenshots**
![imagem](https://user-images.githubusercontent.com/22846996/75634768-67409180-5c08-11ea-8273-de1e2b8a7d70.png)

**Additional context**
I swear I'm not that dirty of a boy, don't listen to Zephy.

**Comment by velddev** [comment]
Fixed
