### ISSUE TITLE
Miki is not responding to two sets of commands (Anime; Donator)

### ISSUE THREAD

**Issue by Bunny-Boo** [veldlabs/miki-bot#632]
**Describe the bug**
Bot is not responding to any of commands from given categories (Anime; Donator). [ I don't know if `>sellkey` and `>redeemkey` work since I didn't donate to Miki. ]

**Expected behavior**
To respond to commands and show info/images depending on what command is meant for.

**Screenshots**
![Screenshot_20200301-230655_Discord](https://user-images.githubusercontent.com/59715817/75634933-42511c00-5c12-11ea-90cb-53bdda0fe523.jpg)
![Screenshot_20200301-230704_Discord](https://user-images.githubusercontent.com/59715817/75634942-5a28a000-5c12-11ea-9707-910f8fa5a264.jpg)

**Comment by velddev** [comment]
All of these are fixed
