### ISSUE TITLE
Miki doesn't DM reminder message

### ISSUE THREAD

**Issue by Bunny-Boo** [veldlabs/miki-bot#633]
**Describe the bug**
Bot sets reminder but it doesn't send reminder once time has passed.

**To Reproduce**
1. Do `>reminder Testing in 15mins`
2. Bot shows that reminder has been set
3. Bot doesn't send reminder message in DM after time has passed

**Expected behavior**
To send reminder message in DMs.

**Screenshots**
![Screenshot_20200301-223327_Discord](https://user-images.githubusercontent.com/59715817/75635025-14200c00-5c13-11ea-80ef-089e530d2205.jpg)
![Screenshot_20200301-223343_Discord](https://user-images.githubusercontent.com/59715817/75635027-18e4c000-5c13-11ea-99d3-0db9098618c2.jpg)

**Comment by adv0catus** [comment]
This appears to be working now.

![](https://i.imgur.com/EX6yGcc.png)
