### ISSUE TITLE
User not found

### ISSUE THREAD

**Issue by Loranis** [veldlabs/miki-bot#634]
When I use ship command it won't respond And if use or someone use on me marry command it says somethig went Wrong and then user not found, I did both syncs the other guy too, still doesnt work. It worked for more than half an year for me

**Comment by velddev** [comment]
Could you contact the discord server support instead for this? https://discord.gg/2whUNP

**Comment by Zephy-o** [comment]
issue was solved, putting two spaces before the @ user mention caused the error
