### ISSUE TITLE
User searching does not return correct user object.

### ISSUE THREAD

**Issue by Bunny-Boo** [veldlabs/miki-bot#636]
**Describe the bug**
Bot doesn't ship with person that used emoji in their nickname, but it ships with first user with such nickname without emoji.

**Expected behavior**
To ship with user whose nickname contains emoji.

**Screenshots**
![Screenshot_20200304-194238_Discord](https://user-images.githubusercontent.com/59715817/75911873-8d587280-5e50-11ea-81e2-47d3dfa00941.jpg)
![Screenshot_20200304-194251_Discord](https://user-images.githubusercontent.com/59715817/75911903-9a756180-5e50-11ea-950c-e4f6e44a9d7d.jpg)

**Comment by Zenulous** [comment]
Fixed with #659
