### ISSUE TITLE
Miki uploading a file "meme.png"

### ISSUE THREAD

**Issue by Shiroi-shi** [veldlabs/miki-bot#649]
**Describe the bug**
When using the >ship command, Miki upload a file "meme.png" after her answer, sometimes it takes a long time for the message to arrive

**To Reproduce**
1. Do >ship someone
2. Wait for the answer
3. A file named "meme.png" is uploaded by Miki just after the answer

**Expected behavior**
No file should be uploaded (I guess?)

**Screenshots**
![image](https://user-images.githubusercontent.com/15214426/76422586-bb383c80-63a5-11ea-8b55-29d24ec3b587.png)

**Comment by adv0catus** [comment]
You and/or the other user needs to use the ‘>syncavatar’ command.

**Comment by lunetokki** [comment]
It stopped doing it a little after I reported it without us having to do >syncavatar but we will do it just in case.
Also when this happened Miki was also not responding when trying to do >ship for some users while she was responding normally for other users and giving the error message if no user was found

**Comment by adv0catus** [comment]
For ship, make sure there isn’t a double space before the user mention.

**Comment by velddev** [comment]
Should be resolved in the latest version
