### ISSUE TITLE
Marriage Mention Bug

### ISSUE THREAD

**Issue by xialight** [veldlabs/miki-bot#65]
![](https://cdn.discordapp.com/attachments/266392738952511498/277937860685070336/unknown.png)
Someone was trying to marry a person but it was given this bug shown above. This is probably a sharding issue since it was fixed when they married at a **different server** .

**Comment by IA-Xerise** [comment]
It's not really a bug, its more like it takes time for the database to sync across the shards.

**Comment by velddev** [comment]
Sharding no longer is an issue since everything related to marriage is hosted on the database now. 

Relating to this issue, It looks like someone is trying to marry a role mention.

**Comment by IA-Xerise** [comment]
Might want to consider adding an error throw for if people mention a role, depending on how much work that would be.
