### ISSUE TITLE
>configrole

### ISSUE THREAD

**Issue by fhg123** [veldlabs/miki-bot#655]
configrols do net get automatically given to a user.

**Comment by velddev** [comment]
What is the query you set up for your role?

**Comment by fhg123** [comment]
>configrole Newbie -automatic:true -level-required:2 -optable:true

**Comment by velddev** [comment]
That seems to be correct syntax, does the user hit level two? It doesn't automatically backfill people above level 2

**Comment by fhg123** [comment]
The User hit level 2 and the Bot do not give the rolle 
The user even hit lvl 3 ant nothing happened

**Comment by fhg123** [comment]
Did you find out why it is not working properly?

**Comment by velddev** [comment]
I haven't had the time yet, apologies.
