### ISSUE TITLE
Profile aren't syncing 

### ISSUE THREAD

**Issue by timcampy118** [veldlabs/miki-bot#66]
https://cdn.discordapp.com/attachments/266392738952511498/278348457406627841/bug2.PNG

**Comment by IA-Xerise** [comment]
You really should add more info than just that if you can.
sidenote: part of it is working 
![image](https://cloud.githubusercontent.com/assets/24828421/22675920/6480dd52-ecb6-11e6-9efb-3bc6345a4185.png)

**Comment by IA-Xerise** [comment]
Looks like another issue similar to https://github.com/velddev/miki/issues/63 where a new account isn't working correctly.

**Comment by timcampy118** [comment]
Reading over #63 and #37, I think 37 is a completely separate issue with the database not updating a user's name. 63 might be similar but if you are correct and that issue was tied into the creation of a new accounts, than that would contradict with this issue as this person has had a account for almost a month now and did not have any issues until now. Something must've change from then until now to cause this. 

Mmm, a idea just popped into my head just now. It might be something to do with with disabling the the accounts commands in the server. Technically, Mekos are labeled under the accounts category. Now whether the code has it like that is a different story. I know for a fact that for this problem and 63's problem, the accounts commands are disabled but Mekos are still working on it. I don't have access to the code but maybe that might be a place to start.

**Comment by velddev** [comment]
@timcampy118 the issue here seems to be that Miki didn't automatically create an account for you. I've got this fixed in 0.1.99

Which is coming out later this week.

**Comment by velddev** [comment]
This was resolved in 0.1.99
