### ISSUE TITLE
Miki doesn't respond to anything

### ISSUE THREAD

**Issue by DragosKemosabe** [veldlabs/miki-bot#664]
Hello , simple question . Added Miki yesterday , worked fine , at the beggining of this day worked fine , but now , doesn't work at all . I tried to kick it and bring it back , didn't change the issue . I tried creating another server and see if it works there but it did not . What can i do ?

**Comment by velddev** [comment]
Hi, we're currently having maintenance on 33% of the discord servers. Please be patient :)

**Comment by DragosKemosabe** [comment]
For how long ?

**Comment by DragosKemosabe** [comment]
How long is this gonna be ?

**Comment by velddev** [comment]
I will send a notification using the announcements channel in https://discord.gg/miki. Please subscribe to that on your server :)

**Comment by DragosKemosabe** [comment]
i subscribed to the announcement channel but i deleted that Miki server , will i still get those notifications or i need to add it back ?

**Comment by velddev** [comment]
You should still get the notifications

**Comment by DragosKemosabe** [comment]
Thanks a bunch . Oh , your bot is awesome btw .
