### ISSUE TITLE
Negative reminder times.

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#673]
**Describe the bug**

There are several reminders on my list that are negative, frozen in time, and aren't being removed (it's been about 2 days).

**To Reproduce**

No clue.

**Expected behavior**

Reminders to be cleared when completed.

**Screenshots**

![](https://i.imgur.com/7gNnMTq.png)

**Comment by velddev** [comment]
Interesting bug. This might be because of the cache ejecting the reminder.
