### ISSUE TITLE
>help bug

### ISSUE THREAD

**Issue by air-sys** [veldlabs/miki-bot#681]
**Describe the bug**
So when you do >help general if you scroll down a small but you will see >calc >changelog >giveaway all sayin Something went wrong!
**To Reproduce**
1. Type >help general and then you should see it

**Expected behaviour**
You should see the Something went wrong

**Comment by exsersewo** [comment]
This is intended behaviour when a translation hasn’t been found for a command.

**Comment by Drummss** [comment]
I think UX improvements can be made here. It's natural for a user to think that something has actually gone from when it tells them as much. Perhaps it would be worth having it say "We are still documenting this!" or something to that effect ^.^

**Comment by Zenulous** [comment]
Will be fixed together with #709
