### ISSUE TITLE
Miki Voting - No Mekos

### ISSUE THREAD

**Issue by Helvot** [veldlabs/miki-bot#697]
**Describe the bug**
Mekos are not being given when voting for miki bot.

**To Reproduce**
1. Go to 'https://top.gg/bot/160105994217586689/vote'
2. Click on vote (with account linked)
3. miki at this point would normally send the mekos'
4. No mekos received nor any confirmation from miki bot that voting was received

**Expected behavior**
A message from miki to thank me for voting and mekos depending on vote streak

**Screenshots**
![Screenshot_20200710-010449_Chrome](https://user-images.githubusercontent.com/68111188/87154699-969b9500-c2b1-11ea-8058-73a2de49aa02.jpg)

**Comment by velddev** [comment]
Issue was resolved: when moving to https://miki.bot, the webhooks didn't register the new domain yet.
