### ISSUE TITLE
>e621 not finding images

### ISSUE THREAD

**Issue by ghost** [veldlabs/miki-bot#699]
**Describe the bug**
Using the >e621 command with any tag(s) in a NSFW channel produces an error stating that "We tried looking what you wanted, but nothing was found."

**To Reproduce**
1. In a NSFW channel, send the message '>e621' followed by any tag(s), for example '>e621 dragon'

**Expected behavior**
In a similar fasion to the >gelbooru command, Miki should sent a message with an image from e621.net that has the tags you specified when sending the message.

**Screenshots**
![Screen Shot 2020-07-31 at 1 27 59 PM](https://user-images.githubusercontent.com/69054396/89065757-e3fba700-d331-11ea-9615-0e9a91a2579c.png)

**Comment by Consmarck** [comment]
I'm having the exact same problem but it's with every other command except rule34.
![image](https://user-images.githubusercontent.com/69879652/90661029-b4dfa380-e214-11ea-8117-c4028870f47e.png)

**Comment by velddev** [comment]
e621 might have an issue, we simply block loli and similar tags on any image command

**Comment by Zenulous** [comment]
Will be resolved in next release
