### ISSUE TITLE
nullref at >showproposals

### ISSUE THREAD

**Issue by Aliya515** [veldlabs/miki-bot#70]
When [misa](266889082204848140) uses >showproposals, it calls a null reference error, this could be several things

* accounts loading is going bad
* database on marriage breaks

Image related: 
![image](https://cloud.githubusercontent.com/assets/13852840/22925652/d4a7cfc0-f2a9-11e6-93d4-3f0ab2a71626.png)

**Comment by velddev** [comment]
Added a description because nukie is a derp

**Comment by nukrie** [comment]
😏
