### ISSUE TITLE
Blackjack game resets without a winner

### ISSUE THREAD

**Issue by poseidon260** [veldlabs/miki-bot#700]
The bug is that while playing blackjack with the bot on discord sometimes after a game has started the commands >blackjack hit/stay or >bj hit/stay don’t work and when you re send the command the bot generates a message saying you need to start a game in order to use the commands I’ve lost over 1 million mekos to this bug and I’ve attached screenshots for reference 
![2D4FEB1F-869B-4DDE-B6C1-3537547A7D1B](https://user-images.githubusercontent.com/69351570/89645956-73cec180-d8ed-11ea-8db8-ccfd0064dc39.png)
![F5DB85ED-19E1-483F-AF8B-8F049E6AB9CF](https://user-images.githubusercontent.com/69351570/89645978-7c26fc80-d8ed-11ea-8af0-fb4ac370bbe6.jpeg)
![94C244ED-A345-460A-B502-AAADC76080E3](https://user-images.githubusercontent.com/69351570/89645981-7cbf9300-d8ed-11ea-9e32-44c05a353e9e.jpeg)

**Comment by velddev** [comment]
Seems to be that it might be you're messaging too quick, and discord is denying the message. We need a better way to retry edit message requests.

**Comment by poseidon260** [comment]
> Seems to be that it might be you're messaging too quick, and discord is denying the message. We need a better way to retry edit message requests.

Hey! Unfortunately I’ve tried to time it every time. I sometimes sent it within 10 seconds sometime within 20 and sometimes within 45 seconds too so I don’t think it’s the timing. But thank you!

**Comment by velddev** [comment]
Hm... Do you have a server invite?

**Comment by poseidon260** [comment]
> Hm... Do you have a server invite?

Yep I have the invite to the support server https://discord.gg/39Xpj7K

**Comment by Zenulous** [comment]
@poseidon260 , reminder if you able to provide more information and/or the server invite. Will close until further notice.
