### ISSUE TITLE
Miki doesn’t acknowledge >rep. 

### ISSUE THREAD

**Issue by adv0catus** [veldlabs/miki-bot#702]
**Describe the bug**
Miki will add rep to the mentioned users but not acknowledge the command.

**To Reproduce**
1. Use >rep @user1 @user2 @user 3
2. Be ignored
3. Do >rep again to confirm you have no rep points left 

**Expected behavior**
Acknowledgment of rep and displaying new rep values 

**Screenshots**

![C7FD0475-9946-463B-8C54-31346D5252DB](https://user-images.githubusercontent.com/10149775/91113531-cdf0b600-e653-11ea-926f-ba5712b5a696.jpeg)

**Comment by Zenulous** [comment]
I could not replicate this bug. Have you tried to rep these users in the same way someday after you posted this issue?
Will close until further notice.
