### ISSUE TITLE
Repeated "Hello! I am Miki! Use >help to check out what I can do! :notes:"

### ISSUE THREAD

**Issue by bekaertruben** [veldlabs/miki-bot#706]
**Describe the bug**
The message "Hello! I am Miki! Use >help to check out what I can do! :notes:" has appeared multiple times in my server without kicking and reinviting Miki.

**To Reproduce**
I don't know. Other servers I'm in don't seem to have the same issue?

**Expected behavior**
For this not to happen, I suppose.

**Screenshots**
![image](https://user-images.githubusercontent.com/43539018/92302432-7a903900-ef6c-11ea-9286-dc8a30a03571.png)

**Additional context**
this is in the #welcome channel

**Comment by bekaertruben** [comment]
It does happen on other servers too
![image](https://user-images.githubusercontent.com/43539018/93249933-56193580-f792-11ea-9ae2-840169bc55e3.png)

**Comment by bekaertruben** [comment]
Don't mention the pings, I got this from another person

**Comment by velddev** [comment]
This should be resolved once we roll out miki.discord 4.0, it is a bit more intelligent on which server to keep and which to remove. This only happens when discord is having issues for the time being, sorry about that. (love the custom avatars btw)

**Comment by bekaertruben** [comment]
Awesome!
Also, very off-topic, but if you meant Tekenen and Bart's avatars, you can make your own at https://picrew.me/image_maker/137904 ;)

**Comment by velddev** [comment]
Haha cool, I tried to make me
![image](https://user-images.githubusercontent.com/13852840/93254625-ebb7c380-f798-11ea-843f-13b19adddc85.png)
