### ISSUE TITLE
Cant use >profile

### ISSUE THREAD

**Issue by Roxaslenobody** [veldlabs/miki-bot#71]
Still unable to use >profile waited a few days to see if it would fix itself but sadly it didnt

**Comment by IA-Xerise** [comment]
Does it give any error? Are you on the miki support discord? If not what is your discord user ID?
you could try `miki.profile` if someone changed miki's prefix.

**Comment by velddev** [comment]
This is a known error, It's more complicated than that.

**Comment by velddev** [comment]
The problem was that he had no avatar.
