### ISSUE TITLE
Miki compliments do not properly use locales

### ISSUE THREAD

**Issue by Zenulous** [veldlabs/miki-bot#714]
**Describe the bug**

Miki compliments do not properly use locales.

**To Reproduce**
1. Use `>compliment` in a non-native Miki locale: a language with translated locales will still use the English default.

![image](https://user-images.githubusercontent.com/45333650/93936890-1ec4fe80-fd27-11ea-88a8-34656130757e.png)

**Comment by velddev** [comment]
It isn't worth to translate all of them
