### ISSUE TITLE
Perms Problem

### ISSUE THREAD

**Issue by ghost** [veldlabs/miki-bot#716]
**The Details of the Perms Problem**
What does work:
Allowing the integrated Miki role  *read/send messages, attach files, use links, see history, use exteral emojis, add reactions* in the __server__ wide perms. 

What should work but doesn't:
Allowing @Miki#6045 herself or her integrated role to *read/send messages, attach files, use links, see history, use exteral emojis, add reactions* in the __channel__ specific perms. 

Why is this a problem?
In a large multi-function server like mine, it is not possible to allow every single bot in all the channels. This is why the bots in my server are managed at the __channel__ level and this works perfectly fine for the many other bots in the server. 
Please fix your bot to respond to __channel__ level perms so I can have it in my server for my members.

**Comment by velddev** [comment]
Fair enough, this seems to be a cache issue for the miki.discord library. Will look into checking if channel overrides are not working as they should. Thanks for the report. Do you have reproduction steps for me?
