### ISSUE TITLE
Can't miki marry, says no slots

### ISSUE THREAD

**Issue by LilithMorningstar** [veldlabs/miki-bot#726]
I miki propossed to someone but when they want to accept miki tells me i have no slots!
I married to 1 other person but seen people married to 5 so why does it say i have no lots

![Screenshot_20210301-155314_Discord](https://user-images.githubusercontent.com/79856007/109515025-e9c39180-7aa6-11eb-90ed-b80d716ea615.jpg)
![Screenshot_20210301-155310_Discord](https://user-images.githubusercontent.com/79856007/109515046-f21bcc80-7aa6-11eb-937a-4b7513a2883e.jpg)

**Comment by adv0catus** [comment]
You need to use the command `>buymarriageslot` to purchase another. You're limited to 5 open slots when your account is created. You can purchase 5 more and if you are a donator, you can purchase an additional 5.

**Comment by LilithMorningstar** [comment]
![Screenshot_20210301-170332_Discord](https://user-images.githubusercontent.com/79856007/109523864-2051da00-7ab0-11eb-9829-9d35aca03e64.jpg)
But i only have 1 slot used, never miki maried before the one i have.
So if you say everyone gets 5 slots i still would have 4 slots to use!

**Comment by ramenu-I** [comment]
Same problem here
