### ISSUE TITLE
Prefix is not working 

### ISSUE THREAD

**Issue by Frostyfox95** [veldlabs/miki-bot#73]
So I changed Mikis' prefix and now when I try to use the new one nothing happens and the old one isn't working either. It just plain doesn't say anything. I'm kinda at a loss of how to fix this I already tried kicking her and reinventing her and it it didn't fix

**Comment by IA-Xerise** [comment]
use `miki.prefix >`

**Comment by Frostyfox95** [comment]
Thank you that fixed it
