### ISSUE TITLE
Miki Bot is offline

### ISSUE THREAD

**Issue by EthanGoatguy** [veldlabs/miki-bot#730]

**Comment by EthanGoatguy** [comment]
> I saw someone ask the same thing a while ago and a user gave them a link, but when I clicked on it now, the page doesn't exist/has probably been deleted already.
> 
> If someone could help, I'd very much appreciate it :)

Oh hold on, I fixed it.
Very sorry for the inconvenience!

**Comment by GerardSmit** [comment]
No problem! Closing as this is fixed.
