### ISSUE TITLE
Day streak

### ISSUE THREAD

**Issue by TeamkillerCG** [veldlabs/miki-bot#731]
As to whether this is a bug or not I am uncertain however I will still post it to be sure. After reaching a 100 day streak the miki bot halts all multipliers. Meaning everyday after 100 continues to give 2100 mikis instead of following the past trend of stacking a multiplier. 

**Expected behavior**
I have a goal to get to 1000 days to see what the streak multiplier would be. I expected it to honestly never stop multiplying. It not having this multiplier after a measly 100 days kinda kills the joy. 
![Screenshot_20210313-203027_Discord](https://user-images.githubusercontent.com/78752757/111055416-3a3dd600-843b-11eb-9981-91d858e004b4.jpg)
![Screenshot_20210313-203049_Discord](https://user-images.githubusercontent.com/78752757/111055419-3f028a00-843b-11eb-8acf-adcf42ef56b6.jpg)

![Screenshot_20210313-203057_Discord](https://user-images.githubusercontent.com/78752757/111055423-45910180-843b-11eb-9814-5add69c2cf53.jpg)

To contact me my discord is Teamkiller_CG#2927

**Screenshots**

**Additional context**

**Comment by Drummss** [comment]
There is a cap on how much you can get from a streak at this current point in time. So it's not a bug, sorry :X

**Comment by TeamkillerCG** [comment]
Any possibility of the cap being removed? It seems like such a waste, you
could have a lot of people competing to have a higher daily gain in money
