### ISSUE TITLE
Background preview images not showing

### ISSUE THREAD

**Issue by Helvot** [veldlabs/miki-bot#739]
**Describe the bug**
When users use >buybackground the response from miki should include an image of the background in the embed for preview, but this image has stopped showing

**To Reproduce**
1. Type >buybackground [number]

**Expected behavior**
Miki responds with an embed, telling you how much the background is and also the command necessary for confirming the background purchase, followed by a preview of what the background looks like.

**Comment by DrFineSir** [comment]
Fixed
