### ISSUE TITLE
Ship nicknames no longer finding users

### ISSUE THREAD

**Issue by Helvot** [veldlabs/miki-bot#740]
**Describe the bug**
When using >ship command, you can no longer find users without pinging them

**To Reproduce**
1. >ship (username) without mentioning them

**Expected behavior**
Miki responds with the >ship command result as per normal but the user doesn't get pinged 

**Screenshots**
![Screenshot_20210721-132438_Discord-Beta](https://user-images.githubusercontent.com/68111188/126489004-3a32c513-113e-4136-999d-0f8956d999e1.jpg)

**Comment by DrFineSir** [comment]
Its quite weird, currently it only works sometimes, with some users, mostly the ones that arent nicked or have emojis in their name.

![image](https://user-images.githubusercontent.com/36110242/126582392-71fedd14-fdcf-484a-bb74-8dba5102e687.png)

![image](https://user-images.githubusercontent.com/36110242/126582404-ac222396-8abf-4e07-9883-feb313d1f8d8.png)

ill investigate it and have it find users a better way.
