### ISSUE TITLE
Flip command images no longer showing

### ISSUE THREAD

**Issue by Helvot** [veldlabs/miki-bot#741]
**Describe the bug**
When using the >flip command, the special Miki coin image reflecting whether the flip was heads or tails no longer shows

**To Reproduce**
1. > Type >flip 1 [Heads/Tails]

**Expected behavior**
Miki responds with an embed stating whether you have won or lost, but in the top right corner also show a Image of the Miki coin with either Heads or Tails showing

**Screenshots**
![Screenshot_20210721-133808_Discord-Beta](https://user-images.githubusercontent.com/68111188/126490875-8a581ce2-57bc-43df-a597-93eef52f1f24.jpg)
![Screenshot_20210721-133744_Discord-Beta](https://user-images.githubusercontent.com/68111188/126490895-b3557d00-bb68-47f6-9390-e10ad4d8aefb.jpg)

**Notes**
- I am unable to find/retrieve an image of what the miki coin looks like as it won't load on my Discord for older commands.

**Comment by DrFineSir** [comment]
Fixed
