### ISSUE TITLE
Buying a background not working for some of the backgorunds

### ISSUE THREAD

**Issue by Creaturehere** [veldlabs/miki-bot#742]
**Describe the bug**
Not showing the price or how to buy background 31

**To Reproduce**
Do the command ">buybackground 31

**Expected behavior**
Should show the price and the confirm to buy it

**Comment by DrFineSir** [comment]
Images are marked as uncommon, in the meanwhile I will add a message stating that this is not available for purchase

**Comment by DrFineSir** [comment]
Need to check with Veld on the info on these images

**Comment by DrFineSir** [comment]
Temp Fix
