### ISSUE TITLE
Disabled >server

### ISSUE THREAD

**Issue by Phanrazak** [veldlabs/miki-bot#77]
Do ``>pasta IAFuckedUp``

**Comment by IA-Xerise** [comment]
![image](https://cloud.githubusercontent.com/assets/24828421/23104430/cb62d234-f69b-11e6-9868-2e8e2aa11eb5.png)


This comment is redundant.

**Comment by IA-Xerise** [comment]
assuming you didnt disable >channel you can just make a new channel and do this:
![image](https://cloud.githubusercontent.com/assets/24828421/25368958/65bf6bf0-294e-11e7-99d9-508113de6f39.png)
