### ISSUE TITLE
Using <@id> in embeds

### ISSUE THREAD

**Issue by Numailia** [veldlabs/miki-bot#80]
Miki is still trying to mention users with <@id> even though all the messages were switched to embeds a long time ago, change this please
![image](https://cloud.githubusercontent.com/assets/18292514/23192657/b4b30c06-f872-11e6-8905-79497ebec84f.png)

**Comment by IA-Xerise** [comment]
Fixed in 0.2.1
![image](https://cloud.githubusercontent.com/assets/24828421/25365689/530ba3fe-2938-11e7-81b0-3b6dcffcf15e.png)
