### ISSUE TITLE
Something went wrong?

### ISSUE THREAD

**Issue by kaelbloodelf** [veldlabs/miki-bot#81]
when using the >nsfw command it gives this error (Something went wrong!) on specific characters, for example hinata from naruto

**Comment by IA-Xerise** [comment]
it works fine if you use the correct tag. the reason she is saying something went wrong is probably because the tag you typed returned no results. 
![image](https://cloud.githubusercontent.com/assets/24828421/23327212/fa126214-fad5-11e6-8100-ef2d00f0a971.png)
