### ISSUE TITLE
When using >profile, username comes up as please change your nickname

### ISSUE THREAD

**Issue by ghost** [veldlabs/miki-bot#82]
When I type in >profile, my username comes up as please change your nickname in the message that miki sends in response. Please help!

**Comment by Phanrazak** [comment]
Please refer to #38. It's currently being worked on

**Comment by IA-Xerise** [comment]
![image](https://cloud.githubusercontent.com/assets/24828421/25368261/35645a74-2949-11e7-8bc5-9dbcbef7675d.png)
![image](https://cloud.githubusercontent.com/assets/24828421/25368267/3ef76d10-2949-11e7-844a-df4807165133.png)
