### ISSUE TITLE
Expansion for marriage slots

### ISSUE THREAD

**Issue by SwaronLmao** [veldlabs/miki-bot#87]
I was preforming marriages with people that I like, but as I try to marry a sixth I see that the limit is 5. I was wondering if we could be able to use the mekos that we gather to purchase extra slots to use and thus, marry other people.

**Comment by davpfre** [comment]
There have been worked on it. The command is going to be called >buymarriageslot

**Comment by rosieneko** [comment]
Closing ticket as this is a feature already being working on.
