### ISSUE TITLE
Bot Not working 

### ISSUE THREAD

**Issue by NIGHTCORE-REM** [veldlabs/miki-bot#88]
in no server no commands will work for a few hours now :(

**Comment by davpfre** [comment]
Can you elaborate the exact issue? Sorry, while problems like these might be irritating, they are not permanently. Rather join the Miki server and state your problem there. I'll be sure help.

**Comment by NIGHTCORE-REM** [comment]
miki is working now thanks

**Comment by davpfre** [comment]
Fine, it's not like you shouldn't open issues here on GitHub. But make sure that the bug can be "regenerated" by other people. Also... next time give the title of the issue a better name than "Bot not working"

Sorry, if I seem harsh, but it is hard to help, if we don't know the problem.

**Comment by NIGHTCORE-REM** [comment]
ok and it it by 2 other people but it seems to be working and and i understand more info for next time if there is ty for ur time
