### ISSUE TITLE
>buymarriageslot Not Enough Mekos when user has Exact amount

### ISSUE THREAD

**Issue by IA-Xerise** [veldlabs/miki-bot#94]
![image](https://cloud.githubusercontent.com/assets/24828421/25367758/d98fa076-2945-11e7-8c62-808a44c59074.png)
![image](https://cloud.githubusercontent.com/assets/24828421/25367765/e6231728-2945-11e7-9873-98917096ca62.png)

**Comment by IA-Xerise** [comment]
![image](https://cloud.githubusercontent.com/assets/24828421/25368688/5d2e3cca-294c-11e7-934f-b52cf6d344bc.png)

**Comment by velddev** [comment]
Fixed for 0.2.2
