### ISSUE TITLE
tried to disable "nsfw"

### ISSUE THREAD

**Issue by Tsiem** [veldlabs/miki-bot#97]
i tried to disable nsfw on a channel and it didnt work
![image](https://cloud.githubusercontent.com/assets/28046075/25427597/5ef2c986-2a73-11e7-9227-1a35283e83c1.png)

**Comment by velddev** [comment]
Thanks I'll look into it!

**Comment by velddev** [comment]
Actually, Nsfw no longer exists, therefore shouldn't be a option.
