### ISSUE TITLE
>syncavatar error

### ISSUE THREAD

**Issue by Jasdavros** [veldlabs/miki-bot#98]
tried to start syncing my avatar and name (though I don't think I need to sync my name) and received the error
![mikierrorsyncavatar](https://cloud.githubusercontent.com/assets/28059996/25445255/eaa06940-2a7b-11e7-8fec-eff828252654.PNG)

**Comment by velddev** [comment]
Seems like Discord couldn't give Miki the data needed. I'll keep it open, do you have a gif or png avatar?

**Comment by Jasdavros** [comment]
Gif

**Comment by velddev** [comment]
Okay, this should also be fixed at 0.2.2
